### ISSUE TITLE
ref type=external in msDesc/additional/listBibl

### ISSUE THREAD

**Issue by laMischke** [cceh/capitularia#1]
@MarcelloPerathoner @domtru @Capitularia-sk 
Problem: Von dem tag `ref type="external"` (mit Links zu Online-Ressourcen) umschlossene Textabschnitte werden nicht angezeigt; 
Bsp.:   `<bibl corresp="#Schmitz_1996">Schmitz 1996, <ref subtype="dmgh"
                                 target="MGH_Capit_N._S._1_S._81" type="external">S.
                            81-83</ref></bibl>`
Hier steht die Seitenangabe innerhalb des ref und wird nicht angezeigt. Das kommt nur sporadisch vor; in der Regel ist das ref ein leeres Element. 
Dass diese refs (bis auf `ref type="external" subtype="Bl"` = Link zur Bibliotheca legum) nicht mehr verarbeitet werden, war (wenn ich mich recht erinnere) Absicht; da wir ohnehin zukünftig nur noch in die Bibliographie verlinken wollen, von wo aus die Nutzer dann auf die jeweilige Online-Ressource zugreifen können, könnten sie eigentlich wegfallen, aber es gibt bestimmt einen Grund, warum sie nur deaktiviert wurden.
Wie könnte man das Problem lösen?

**Comment by MarcelloPerathoner** [comment]
Das Problem ist: bibl[@corresp] erzeugt ein <a>. Wenn ref jetzt noch ein <a> erzeugt, haben wir verschachtelte <a>'s und das ist ungültiges HTML.

**Comment by MarcelloPerathoner** [comment]
Jetzt wird der Inhalt von ref immer angezeigt, aber ein link wird nur erzeugt wenn subtype=Bl ist und der ref nicht innerhalb eines bibl[@corresp] ist.
