### ISSUE TITLE
Schematron: Nach milestone unit="capitulatio" alle corresps immer mit "inscriptio_c"

### ISSUE THREAD

**Issue by laMischke** [cceh/capitularia#105]
@Capitularia-sk @domtru @skheinen 

Nachdem Martina das Repository https://github.com/cceh/capitularia-tei-qm geschlossen hat, ist nur noch ein Issue übriggeblieben, für das ihr keine Lösung einfiel (s.u.).

@MarcelloPerathoner : Vielleicht fällt Dir ein, wie man das als Abfrage in Schematron einbauen könnte?

Zwischen einem milestone unit="capitulatio" und dem dazugehörigen anchor mit der xml:id, die "capitulatio_finis" enthält, müssen alle @corresp den Namensbestandteil "inscriptio_c" enthalten.

Bsp. aus wolfenbuettel-hab-blankenb-130:
Zwischen
milestone xml:id="wolfenbuettel-hab-blankenb-130-70v-capitulatio-1" unit="capitulatio" spanTo="#capitulatio-finis_13.4"

und
anchor xml:id="capitulatio-finis_13.4":
z.B.
ab rend="coloured" type="meta-text" xml:id="wolfenbuettel-hab-blankenb-130-70v-8" corresp="BK.174_inscriptio_c"

**Comment by MarcelloPerathoner** [comment]
Das müßte funktionieren:

```
<schema xmlns="http://purl.oclc.org/dsdl/schematron">
  <ns uri="http://www.tei-c.org/ns/1.0" prefix="tei" />
  <pattern>
    <rule context="tei:*[@corresp and not (contains (@corresp, 'inscriptio_c'))]">
      <report test="following::tei:anchor[concat ('#', @xml:id) = current()/preceding::tei:milestone[@unit='capitulatio'][1]/@spanTo]">
        @corresp without "inscriptio_c" inside a capitulatio
      </report>
    </rule>
  </pattern>
</schema>
```

**Comment by laMischke** [comment]
@Capitularia-sk @domtru 
Die Abfrage ist aber noch nicht in das Schematron übernommen, oder? Ich habe gerade an der Datei wolfenbuettel-hab-blankenb-130 einen Test gemacht ("_inscriptio-c" an zwei Stellen gelöscht), und es kam keine entsprechende Meldung.
