### ISSUE TITLE
Änderung bei handShift

### ISSUE THREAD

**Issue by laMischke** [cceh/capitularia#108]
@Capitularia-sk @domtru @skheinen 

Bitte die Formulierung in der automatisch bei einem handShift generierten Fußnote ändern zu:
„Ab diesem Wort Wechsel der Schreiberhand, vgl. die Vorbemerkung“ (statt "Ab hier ...", da mißverständliche Formulierung).
Außerdem: Bitte auch die bei handShift generierte Fußnote mit einer evtl. vorhandenen weiteren note oder automatisch generierten Fußnote in eine Anmerkung zusammenziehen - wie in den anderen Fällen, in denen mehrere Fußnoten, die an dasselbe Wort angehängt würden, zu einer Anmerkung zusammengefasst werden.

**Comment by MarcelloPerathoner** [comment]
Die Zusammenziehung sollte bereits funktionieren. Falls nicht, bitte ein Beispiel nennen wo es nicht funktioniert. Ich konnte keine Beispiele finden.
