### ISSUE TITLE
Inscriptiones in der Datei "BK Textzeuge"

### ISSUE THREAD

**Issue by domtru** [cceh/capitularia#109]
@laMischke @Capitularia-sk @skheinen 

In der Datei „BK-Textzeuge“ (/afs/rrz.uni-koeln.de/vol/www/projekt/capitularia/volumes/005/Britta) müssen ein paar Anpassungen vorgenommen werden, die automatisiert werden könnten.

Alle leeren „ab meta-text“-Elemente müssen entfernt werden.

Jede Kombination von arabischer Zahl und Punkt (z.B. „1.“, „2.“ etc.) – sofern sie nicht schon in einem „ab meta-text“ steht! – muss in einen eigenen „ab meta-text“ gepackt werden. Diese Zahl-Punkt-Kombination steht momentan innerhalb eines „ab text“: 
`<ab xml:id="BK_TXT.155_4" corresp="BK.155_4" type="text">`4. De causa…

Die „4.“ muss aus diesem „ab text“ herausgezogen werden und in einen eigenen „ab meta-text“ dem „ab text“ vorangestellt werden: 

`<ab xml:id="BK_TXT.155_4_inscriptio" corresp="BK.155_4_inscriptio" type="meta-text">`4.`</ab>` `<ab type=“text“>`…..`</ab>`

Die xml-id dieses „ab meta-text“ und das corresp werden also um „_inscriptio“ erweitert. 

Man könnte die Zahl-Punkt-Kombination automatisiert mit einem „ab meta-text“ versehen. Allerdings muss dann das öffnende tag des „ab text“ hinter diesen neu entstandenen „ab meta-text“ gesetzt werden.

**Comment by MarcelloPerathoner** [comment]
Erledigt. Allerdings hab ich diese Datei hier geändert:

/afs/rrz.uni-koeln.de/vol/www/projekt/capitularia/http/docs/cap/intern/Transkriptionen/BK_Text_Superstruktur/BK-Textzeuge.xml

In Brittas Verzeichnis ist nur eine Kopie. Soll die auch geändert werden?
