### ISSUE TITLE
Dateien werden nicht im Kollationstool angezeigt

### ISSUE THREAD

**Issue by laMischke** [cceh/capitularia#110]
@Capitularia-sk @domtru @skheinen 

Für unseren Arbeitskurs haben wir ein paar Testdateien angelegt, die nicht auf der Homepage veröffentlicht werden sollen, mit denen wir aber gerne im Kollationstool arbeiten würden.
Sie werden dort aber nicht angezeigt, obwohl sie im publ-Ordner stehen und auch eine andere xml-id haben als die normalen Dateien, aus denen sie gebastelt sind. Wir müssen also irgendetwas Anderes vergessen oder falsch gemacht haben ....

Es handelt sich um folgende Dateien (in mss/publ):
kurs_paris-bn-lat-10758.xml
kurs_selestat-bh-14.xml
kurs_st-gallen-sb-728.xml

Drei weitere sollen noch folgen; wir warten aber erstmal ab, woran es liegt, bevor wir neue erstellen!
Da der Termin für den Kurs schon am Donnerstag ist, wären wir dankbar für eine schnelle Rückmeldung.

**Comment by MarcelloPerathoner** [comment]
Funktioniert bei mir. Ich habe im Page Generator "Extract Metadata" aufgerufen und die Mss. dann im Browser angesehen. Schiebt doch mal die anderen drei Dateien rein.

**Comment by laMischke** [comment]
Ja, jetzt funktioniert's auch bei mir! Du hast außer "Extract Metadata" nichts gemacht, oder doch?

**Comment by MarcelloPerathoner** [comment]
Ich habe die Mss. alle mal angesehen um festzustellen welche BKs sie enthalten.
