### ISSUE TITLE
Änderung in mss-header.xsl

### ISSUE THREAD

**Issue by laMischke** [cceh/capitularia#111]
@Capitularia-sk @domtru @skheinen 

Das Skript mss-header.xsl generiert als Überschrift zu dem Abschnitt mit der Hs.-Beschreibung auf jeder Seite den Standardtext "Beschreibung nach Mordek", wenn der erste Eintrag in der listBibl "Mordek 1995" ist.
- Frage: Warum steht bei paris-bn-lat-3877 trotzdem der Standardtext, obwohl Mordek nicht der erste Eintrag der Bibliographie ist?
- Änderungswunsch: Gibt es eine Möglichkeit, den Text "Beschreibung nach ..." individuell zu formulieren, wenn die Beschreibung NICHT von Mordek stammt?  Etwa so ähnlich wie bei unseren Blogposts zur "Handschrift des Monats", wo wir die Möglichkeit haben, mit "cite as author" jeden beliebigen Namen anzugeben?

**Comment by MarcelloPerathoner** [comment]
Die Formulierung wird jetzt aus title[@type='sub'] herausgelesen.
