### ISSUE TITLE
Responsivität der Website: Sidebar "Archiv" soll nicht als Erstes angezeigt werden (bei Blogbeiträgen?)

### ISSUE THREAD

**Issue by laMischke** [cceh/capitularia#116]
@Capitularia-sk @domtru @skheinen 

Eine Bitte von Herrn Ubl: Wenn man die Website auf dem Handy aufruft, erscheint zuerst die Sidebar "Archiv". Das sollte nicht so sein, weil es sich dabei um das Unwichtigste der Seite handelt. (Gemeint ist wahrscheinlich: nur bei den Blogbeiträgen; bei den übrigen Seiten ist das Erscheinen der Sidebar an erster Stelle ja sinnvoll.) 
Kann man das ändern?

**Comment by MarcelloPerathoner** [comment]
Die Sidebar ist auf dem Desktop immer rechts vom Content und Mobil immer vor dem Content. Wenn man dieses für eine einzelne Seite ändern möchte, dann muß man sowohl PHP als auch CSS extra für diese Seite schreiben. Das ist aufwendig und schwer zu warten. 

Alternativ könnte man Widgets für "Kategorien" und "Archiv" schreiben, die wie unsere Menus zusammenklappbar sind. (Oder unsichtbares Markup in die Seite einfügen und das schon vorhandene Dynamische Menu verwenden.) Das wäre die bessere Lösung.
