### ISSUE TITLE
Verdoppelte Handschrift vatikan-bav-pal-lat-582

### ISSUE THREAD

**Issue by Capitularia-sk** [cceh/capitularia#121]
Im Kollationstool erscheint die Handschrift Vatikan Pal. lat. 582 bei Auswahl doppelt, auch bei den Ergebnissen der Kollation. Der einzige Unterschied zwischen den beiden Versionen besteht darin, wie die Handschrift angezeigt wird: die erste Fassung als "vatikan-bav-pal-lat-582", die zweite leicht verkürzt als "vatikan-pal-lat-582". 
Eine Suche in der xml Datei der Hs. ergab keinen Treffer für die Zeichenfolge "vatikan-pal-lat-582", ebenso eine Suche im gesamten publ\mss Ordner.

**Comment by MarcelloPerathoner** [comment]
Es gibt eine Referenz zu "vatikan-pal-lat-773" in vatikan-bav-pal-lat-773.xml. Ist das korrekt?

**Comment by MarcelloPerathoner** [comment]
Veraltete Referenz gelöscht. Scheint nun nicht mehr auf (wenigstens nicht in BK.186_1).
