### ISSUE TITLE
Fehler in der öffentlichen Version des Kollationstools

### ISSUE THREAD

**Issue by laMischke** [cceh/capitularia#126]
@Capitularia-sk @domtru 

Wenn man BK 159 c. 3 in der öffentlichen Version des Kollationstools (https://capitularia.uni-koeln.de/tools/collation/) aufruft, wird die Hs. vatikan-bav-chigi-f-iv-75 nicht angezeigt; in der internen Version (/wp-admin/index.php?page=cap_collation_dashboard) aber schon!?! Ist bisher der einzige Fall, wo das aufgefallen ist; keine Ahnung, ob es öfters vorkommt ...

**Comment by MarcelloPerathoner** [comment]
Versucht mal diese Zeile zu korrigieren:

&lt;ab type="text" xml:id="vatikan-bav-chigi-f-iv-75-92r-2" corresp="BK.159_2 159_3"&gt;

ob es dann immer nioch nicht geht?
