### ISSUE TITLE
Kapitularienseitengenerator / bibl-Element in name bei den Kapitularienseiten

### ISSUE THREAD

**Issue by domtru** [cceh/capitularia#133]
@laMischke @Capitularia-sk 

Zwei kleine Änderungen/Reparaturen:

1. Der Kapitularienseitengenerator funktioniert nicht mehr. Egal, welche Aktion man ausführen möchte, es wird eine Fehlermeldung angezeigt.

2. Bei den name-Attributen in den xml-Dateien der Kapitularienseiten sollen bibl-Elemente (mit corresp) zugelassen werden. Aus diesen bibl-Elementen soll dann ein Link in die Bibliographie zum entsprechenden Titel generiert werden, also genauso, wie es momentan innerhalb der notes funktioniert.

**Comment by MarcelloPerathoner** [comment]
Funktioniert jetzt auch bei Kapitularienseiten.

**Comment by laMischke** [comment]
@Capitularia-sk @domtru 

Zu 2.: Die Verlinkung über bibl-Elemente in name funktioniert jetzt zwar, aber die Darstellung in HTML hat noch Mängel; siehe die Kapitularienseiten mordek-nr-14, mordek-nr-15, mordek-nr-24 (Seeliger 1894 rutscht in die falsche Tabellenspalte und die Seitenangabe danach wird nicht ausgegeben).
