### ISSUE TITLE
mss_by_cap.xml in ein TEI-nahes Format konvertieren.

### ISSUE THREAD

**Issue by MarcelloPerathoner** [cceh/capitularia#136]
Die Datei mss_by_cap.xml soll in ein TEI-nahes Format konvertiert werden. Abhängige Stylesheets sollen angepaßt werden.

**Comment by MarcelloPerathoner** [comment]
xml-Datei: mss_by_cap

<Kapitularien> -> <list>
<Eintrag> -> <item>
<Kapitular> -> <title>
id -> n
<hss> -> <msIdentifier>
url -> xml:id
<siglum> -> <witness> mit der Sigle als Attribut, also: <witness xml:id=“A“> (bei diesem Element bin ich unsicher, ob man es wirklich braucht [was sagt die xsl?], wenn nicht, dann löschen)
<note> kann so bleiben
<ref type="external"> kann so bleiben

Die publ-Attribute können m.E. wegfallen, da Du ja ohnehin abprüfen lässt, ob eine Datei publ ist oder nicht.

Unsicher bin ich mir, ob das list-Attribut bei manchen Einträgen wirklich gebraucht wird. Das müsste man ja durch einen Blick in die xsl erfahren können. Wenn es nicht gebraucht wird, dann löschen.

Im Moment ist die Datei sehr durcheinander. Nichts ist geordnet. Könnte man gleiche id- bzw. n-Einträge zueinander sortieren und die Datei insgesamt nach BK- bzw. Mordek-Nummern ordnen? Das wäre sehr hilfreich und wesentlich übersichtlicher.

**Comment by MarcelloPerathoner** [comment]
Eine erste Konvertierung liegt vor, in der Datei mss_by_cap_tei.xml a.a.O.

Die Datei ist sortiert nach BK-Nr und dann nach xml:id. 

Die Titel der Manuskripte werden nicht benötigt wenn eine xml:id vorhanden ist. Der Titel kann dann woanders nachgeschlagen werden.

Die Sigle wird nicht benötigt.

@status wird nicht benötigt. @list wird auch nicht benötigt. Diese Attribute sind Wordpress schon bekannt.

Ist das Format so in Ordnung?

**Comment by domtru** [comment]
Lieber Marcello,
vielen Dank für die schnelle Bearbeitung. Das sieht sehr gut aus, vor allem wesentlich übersichtlicher und schlanker als vorher! Die Datei kann gerne die alte ersetzen. Beim allerersten Eintrag habe ich noch das n-Attribut befüllt, da es leer war.

**Comment by domtru** [comment]
@laMischke @Capitularia-sk 

Vielen Dank für die Änderungen! Es sind noch ein paar Kleinigkeiten zu ändern in der XSL:

1. Die notes werden momentan nicht ausgegeben. Diese müssten in kleinerer Schrift unterhalb des Namens des Kapitulars stehen.
2. Die verlinkten Ansegis-Einträge werden nicht nur von einem msIdentifier, sondern auch von einem title-Element umgeben und wohl deswegen nicht ausgegeben. Das title-tag muss weg und die refs entsprechend als Link erscheinen.
3. Die Signaturen der Hss. enthalten zu viele Informationen, weil wohl der <title type="main" xml:lang="ger"> der Hss.seiten ausgelesen wird. Hier besser den <title type="main"> im head nehmen, der beihaltet nur die reine Signatur.
4. Lassen sich die "Kapitularien" unter "Weitere bei Mordek erwähnte Kapitularien und Ansegis" alphabetisch sortieren?

**Comment by MarcelloPerathoner** [comment]
Eine neue Datei manuscripts.xml wurde erzeugt. Diese enthält eine Liste aller Handschriften mit Titel und xml:id, auch solche für die keine Handschriftendatei existiert. 

In der Datei mss_by_cap.xml können nun auch &lt;note>s für Handschriftenzuweisungen vergeben werden, z.B. "(nur Eidesformel)", da diese eigentlich nicht in den Handschriftzentitel gehören.

Ich mußte die Original-Datei leider noch einmal konvertieren, zwischenzeitliche Änderungen sind dabei verloren gegangen.

**Comment by MarcelloPerathoner** [comment]
In der Datei mss_by_cap.xml (bzw. manuscripts.xml) sind noch einige Handschriftentitel zu überprüfen: paris-bn-lat-2389 paris-bn-lat-4761-1-2 paris-bn-lat-1231.

**Comment by domtru** [comment]
Vielen Dank für alle Umarbeitungen! Eine Kleinigkeit noch: Kann man die Notes, die unter den Kapitularientiteln stehen, unterhalb der BK-Nummer ausgeben? Momentan werden Titel und Nr. durch die Note getrennt.

 

Beste Grüße

Dominik

 

Von: Marcello Perathoner <notifications@github.com> 
Gesendet: Montag, 3. Februar 2020 11:47
An: cceh/capitularia <capitularia@noreply.github.com>
Cc: domtru <dtrump1@uni-koeln.de>; Assign <assign@noreply.github.com>
Betreff: Re: [cceh/capitularia] mss_by_cap.xml in ein TEI-nahes Format konvertieren. (#136)

 

In der Datei mss_by_cap.xml (bzw. manuscripts.xml) sind noch einige Handschriftentitel zu überprüfen: paris-bn-lat-2389 paris-bn-lat-4761-1-2 paris-bn-lat-1231.
