### ISSUE TITLE
Fehler auf Kapitularienseiten

### ISSUE THREAD

**Issue by domtru** [cceh/capitularia#141]
@laMischke @Capitularia-sk 

Bei den Kapitularienseiten werden nun die Links auf externe Ressourcen nicht mehr ausgegeben (Element: name). Zudem fehlen die Stift-Symbole hinter den Handschriften als Zeichen, dass es eine Transkription gibt, die darüber direkt angesteuert werden kann. Oder hängen diese Fehler mit der Erledigung von issue #79 zusammen?

**Comment by MarcelloPerathoner** [comment]
Der Shortcode [if_transcribed] geht nicht mehr, da Wordpress nun keine TEI-Dateien mehr zu sehen bekommt sondern nur noch HTML. Es muß ein Interface zum API-Server geschaffen werden.
