### ISSUE TITLE
Marker für nota / glossa einführen

### ISSUE THREAD

**Issue by MarcelloPerathoner** [cceh/capitularia#145]
Marker für nota / glossa einführen. Vielleicht ein "M" und "G" icon neben der @corresp-Anzeige unter dem Kapitularien-Titel.

**Comment by MarcelloPerathoner** [comment]
Example: <tei:ab rend="nota glossa">
Found combinations:
```
glossa
nota
glossa nota
nota glossa
coloured glossa
coloured nota
```

**Comment by MarcelloPerathoner** [comment]
[N] und [G] erscheinen neben der @corresp Anzeige. Falls eine andere Anzeige gewünscht wird, bitte wieder öffnen.

**Comment by laMischke** [comment]
@Capitularia-sk @domtru 

Ein bisschen auffälliger darf es schon sein; und um es besser von den corresps zu unterscheiden, lieber in einer eigenen Zeile. Einen Vorschlag hänge ich an!
Ist das so umsetzbar, in den Capitularia-Farbtönen?
[Vorschlag_Glossa-Notazeichen.pdf](https://github.com/cceh/capitularia/files/4579735/Vorschlag_Glossa-Notazeichen.pdf)

**Comment by laMischke** [comment]
@Capitularia-sk @domtru 
Gefällt uns gut, danke!
Wie üblich, ein paar Folgewünsche:
- Statt "Nota" oder "Glossa" beim Mouseover anzeigen: "Der Textabschnitt ist annotiert" bzw. "Der Textabschnitt ist glossiert"
- Nach dem Zeichen immer ein Zeilenwechsel, auch wenn kein corresp folgt
- In der Legende ergänzen: N = Annotation, G = Glossierung
