### ISSUE TITLE
gap in del innerhalb von subst

### ISSUE THREAD

**Issue by domtru** [cceh/capitularia#153]
@laMischke @Capitularia-sk 

Bei einem leeren, d.h. ohne Attribute versehenen gap-Element in del bei subst wird das in der HTML-Präsentation folgendermaßen ausgegeben: "[††††††]s" für `<subst><del><gap/>s</del>...</subst>`. Die sechs Kreuze sind aber nirgends angegeben und daher verwirrend. Gemäß der Legende bei der Sidebar und den Transkriptionsrichtlinien muss hier stattdessen nur ein Kreuz in eckigen Klammern erscheinen.

**Comment by laMischke** [comment]
@Capitularia-sk @domtru 
Bitte noch anpassen: Jetzt wird der gap innerhalb von del zwar korrekt nur zu [†] verarbeitet, aber danach folgt ein Leerzeichen, was innerhalb eines Wortes irritierend ist; Bsp.: den-haag-rmw-10-d-2: 
```
<subst>
               <del><gap/>na<gap/></del>
               <add>unani</add>
            </subst>miter
```
wird ausgegeben als "korr. aus [†] na[†] miter"; richtig wäre "korr. aus [†]na[†]miter".

**Comment by MarcelloPerathoner** [comment]
Vielleicht liegt es an der Font, die nach eckiger Klammer ziemlich viel Freiraum läßt. Da kann ich nichts machen (außer die Font zu wechseln.)
