### ISSUE TITLE
Kollationstool: Änderung bei Normalisierung von ae/e/e-caudata

### ISSUE THREAD

**Issue by domtru** [cceh/capitularia#157]
@laMischke @Capitularia-sk 

Das Kollationstool normalisiert die Orthographie der Handschriften automatisch zu "e", egal, ob in der Handschrift "ae", "e" oder e-caudata (ę) steht. Das ist für die Überprüfung der Orthographie unvorteilhaft. Ist es daher möglich, die Orthographie in diesen Fälle nicht zu normalisieren? D.h., das Tool gibt die Orthographie der Hss. aus, zeigt ae/e/e-caudata aber nicht als Varianz an, weil dies das Kollationsergebnis nur unübersichtlicher machen würde.

**Comment by MarcelloPerathoner** [comment]
Folgende Normalisierungen werden nun nicht mehr angezeigt sondern nur noch im Hintergrund verwendet:
```
ae=e
ę=e
j=i
v=u
```
