### ISSUE TITLE
bitte raussuchen: Handschriften, wo Kapitel auf mehrere abs verteilt sind

### ISSUE THREAD

**Issue by domtru** [cceh/capitularia#160]
@laMischke @Capitularia-sk 

Bitte über alle Handschriftendateien hinweg suchen und eine Liste generieren: Handschriften, in denen es zweimal das gleiche corresp gibt, wobei ein corresp innerhalb eines milestones (type span) steht und es kein prev/next gibt.

**Comment by MarcelloPerathoner** [comment]
Hier ist die Liste. Ich habe obiges interpretiert als "wobei MINDESTENS ein corresp innerhalb eines milestones steht".

```
heiligenkreuz-sb-217.xml Ansegis.3_inscriptio no-next
kopenhagen-kb-1943-4.xml BK.138_6 no-next
kopenhagen-kb-1943-4.xml BK.140_inscriptio no-next
london-bl-egerton-269.xml BK.140_5 no-prev
muenchen-bsb-lat-3853.xml Ansegis.3_inscriptio no-next
newhaven-bl-413.xml BK.278_1_inscriptio no-prev
paris-bn-lat-4626.xml BK.141_1 no-prev
paris-bn-lat-4626.xml BK.141_1 no-next
paris-bn-lat-4628.xml BK.141_1 no-prev
paris-bn-lat-4628.xml BK.141_1 no-next
paris-bn-lat-4628a.xml BK.192_13 no-next
paris-bn-lat-4628a.xml BK.192_14 no-next
paris-bn-lat-4628a.xml BK.192_15 no-next
paris-bn-lat-4631.xml BK.141_7 no-next
paris-bn-lat-4631.xml BK.141_14 no-next
paris-bn-lat-4631.xml BK.191_3 no-prev
paris-bn-lat-4631.xml BK.191_4 no-prev
paris-bn-lat-4631.xml BK.192_13 no-prev
paris-bn-lat-4631.xml BK.192_14 no-prev
paris-bn-lat-4631.xml BK.192_inscriptio no-next
paris-bn-lat-4631.xml BK.192_13 no-next
paris-bn-lat-4631.xml BK.192_14 no-next
paris-bn-lat-4631.xml BK.192_15 no-next
paris-bn-lat-4631.xml BK.193_1 no-prev
paris-bn-lat-9654.xml BK.191_8 no-next
simancas-ag-pr-29-6.xml BK.45_4 no-prev
simancas-ag-pr-29-6.xml BK.45_5 no-prev
simancas-ag-pr-29-6.xml BK.45_4 no-next
simancas-ag-pr-29-6.xml BK.45_5 no-next
st-paul-abs-4-1.xml BK.140_5_inscriptio no-next
st-paul-abs-4-1.xml BK.140_5 no-next
vatikan-bav-pal-lat-582.xml BK.191_8 no-next
wolfenbuettel-hab-blankenb-130.xml BK.150_2 no-prev
wolfenbuettel-hab-blankenb-130.xml BK.150_2 no-next
```

**Comment by Capitularia-sk** [comment]
Beim Durchgehen der Liste haben wir bemerkt, dass wir angesichts der vielfältigen Kombinationen, in denen das Problem auftreten kann (und einer weiteren potentiellen Fehlerquelle - eine fehlende xml:id) doch noch weitere Varianten der Abfrage bräuchten. 

Falls die unten beschriebenen Abfragen zu komplex sind, wäre eine einfache Lösung zunächst folgende Abfrage:

"Alle Handschriftenseiten identifizieren, in denen die Anzahl der prev-Elemente innerhalb des body ungleich der Anzahl der next-Elemente ist." (Dann muss da irgendwo mindestens eins fehlen; Problem: falls wir von jeder Sorte eins vergessen haben, fällt das so nicht auf)

Die komplexere Abfrage müsste folgendes prüfen:

"Prüfe für jedes next-Element im body, ob die folgenden Bedingungen zutreffen:
(a) Das das next-Element umschließende Element [das kann ein ab oder ein milestone type=span sein] hat ein eigenes xml:id Element [= N].
(b) Das im next-Element genannte Ziel [= P] besitzt ebenfalls ein eigenes xml:id Element [nämlich mit dem Wert P]
(c) In P gibt es ein prev-Element mit dem Ziel N
(d) Sowohl in N wie in P gibt es ein corresp-Element, dessen Wert identisch ist"

Da wir jeweils next oder prev vergessen haben können, müsste die Abfrage sinngemäß auch für alle prev-Elemente durchgeführt werden. Es kann vorkommen, dass nicht nur 2, sondern auch 3 (oder mehr?) Abschnitte verknüpft sind. In dem Fall sollten wir so verfahren sein, dass der 1. Abschnitt ein next, der 2. ein prev (zurück) und ein next (vor), der 3. schließlich nur ein prev enthält. Das sollte aber wohl die Verarbeitung der obigen Abfrage nicht stören.

Wir bräuchten dann eine Liste von allen Fällen, in denen mindestens eine der drei Bedingungen nicht erfüllt wird.

NB Wo genau die prev/next-Elemente stehen, ist bei beiden Abfragen irrelevant; sie können, müssen aber nicht in einem milestone vom type=span stehen.

**Comment by MarcelloPerathoner** [comment]
modena-bc-o-i-2.xml BK.193_inscriptio modena-bc-o-i-2-181v-10 next-target-no-corresp
modena-bc-o-i-2.xml BK.193_1_inscriptio modena-bc-o-i-2-181v-9 prev-target-no-corresp
muenchen-bsb-lat-3853.xml BK.157_1_inscriptio Ansegis.1_79bis_inscriptio muenchen-bsb-lat-3853-245v-2 prev-target-no-next
muenchen-bsb-lat-4460.xml BK.139_10 muenchen-bsb-lat-4460-23r-1_2 prev-target-no-next
muenchen-bsb-lat-4460.xml BK.139_10 muenchen-bsb-lat-4460-23r-1_2 prev-target-no-corresp
muenster-sa-msc-vii-5201.xml BK.141_12 muenster-sa-msc-vii-5201-55-16_1 next-no-target
muenster-sa-msc-vii-5201.xml BK.141_12 muenster-sa-msc-vii-5201-55-16_1 next-target-no-prev
muenster-sa-msc-vii-5201.xml BK.141_12 muenster-sa-msc-vii-5201-55-16_1 next-target-no-corresp
paris-bn-lat-10758.xml BK.192_14 paris-bn-lat-10758-267-2_2 prev-target-no-next
paris-bn-lat-10758.xml BK.192_14 paris-bn-lat-10758-267-2_2 prev-target-no-corresp
paris-bn-lat-4626.xml BK.141_inscriptio_1 paris-bn-lat-4626-68-5_1 next-target-no-prev
paris-bn-lat-4626.xml BK.141_12 paris-bn-lat-4626-70-3_1 next-target-no-prev
paris-bn-lat-4626.xml BK.141_12 BK.141_13 paris-bn-lat-4626-70-2 prev-target-no-corresp
paris-bn-lat-4628.xml BK.141_12 paris-bn-lat-4628-41r-16_1 next-target-no-prev
paris-bn-lat-4628.xml BK.141_14 paris-bn-lat-4628-41r-20_1 next-target-no-prev
paris-bn-lat-4628.xml BK.141_21 paris-bn-lat-4628-41v-4_2 prev-no-target
paris-bn-lat-4628.xml BK.141_21 paris-bn-lat-4628-41v-4_2 prev-target-no-next
paris-bn-lat-4628.xml BK.141_21 paris-bn-lat-4628-41v-4_2 prev-target-no-corresp
paris-bn-lat-4628a.xml BK.142_1 paris-bn-lat-4628a-155rb-1_8 prev-target-no-next
paris-bn-lat-4628a.xml BK.142_1 paris-bn-lat-4628a-155rb-1_8 prev-target-no-corresp
paris-bn-lat-4638.xml BK.184_a BK.184_b paris-bn-lat-4638-72v-3 prev-target-no-corresp
paris-bn-lat-9654.xml BK.260_prolog paris-bn-lat-9654-73v-5_1 next-target-no-prev
paris-bn-lat-9654.xml BK.260_prolog paris-bn-lat-9654-73v-5_1 next-target-no-corresp
paris-bn-lat-9654.xml BK.260_prolog no-xml-id
paris-bn-lat-9654.xml BK.260_prolog no-xml-id
st-paul-abs-4-1.xml BK.141_12 st-paul-abs-4-1-178ra-4_1 next-target-no-prev

**Comment by domtru** [comment]
Vielen Dank für die Liste, das hat uns sehr geholfen! Wir hätten nun gerne, dass der Suchlauf zwecks Überprüfung nochmals gestartet wird und dabei auch die Dateien im "InArbeit"-Ordner berücksichtigt werden. So können wir sicherstellen, dass uns nichts entgangen ist. Danke!

**Comment by MarcelloPerathoner** [comment]
Hier ist noch was:
```
vatikan-bav-vat-lat-4982_NK_2.xml BK.268_a_1 vatikan-bav-vat-lat-4982-109v-7 next-target-no-prev
vatikan-bav-vat-lat-4982_NK_2.xml BK.268_a_1 vatikan-bav-vat-lat-4982-109v-7 next-target-no-corresp
```

**Comment by Capitularia-sk** [comment]
Prima, dann haben wir jetzt alle Dateien einmal auf Vordermann gebracht - vielen Dank!!
