### ISSUE TITLE
Text für Verlinkung auf Digitalisat bei der BML Florenz ergänzen

### ISSUE THREAD

**Issue by laMischke** [cceh/capitularia#163]
@Capitularia-sk @domtru 

Auf der Handschriftenseite florenz-bml-plut-89-sup-86 wird bei der Verlinkung auf das Digitalisat nur das Zeichen für einen externen Link angezeigt. Der Link ist http://mss.bmlonline.it/s.aspx?Id=AWOMMVTDI1A4r7GxMQ_u&amp;c=Leges%20Langobardorum#/book; bitte als Text anzeigen: [Digitalisat verfügbar bei] "Biblioteca Medicea Laurenziana".

**Comment by domtru** [comment]
Bei der Hs. Poitiers 512 (poitiers-mfm-512) bitte eintragen: "[Digitalisat verfügbar bei] "Médiathèque François Mitterrand". Link: https://www.bm-poitiers.fr/Default/doc/SYRACUSE/4057290/tome-lvi-cog-cyp-veme-serie-dom-fonteneau
