### ISSUE TITLE
Links ausgeben Gesamtliste Handschriften

### ISSUE THREAD

**Issue by domtru** [cceh/capitularia#166]
@Capitularia-sk @laMischke 

Momentan werden die Links nach dem Muster "ref type="internal" subtype="mss" target="slug-mss" in der Gesamtliste (ueberblick_mordek.xml) nicht mehr ausgegeben.

**Comment by MarcelloPerathoner** [comment]
Die Datei ueberblick_mordek.xml befand sich nicht in TEI-Namespace. Anfang und Ende der Datei wurden deshalb angepaßt um mit den anderen Dateien kompatibel zu sein.
