### ISSUE TITLE
Das Kollationstool funktioniert nicht in Google Chrome

### ISSUE THREAD

**Issue by MarcelloPerathoner** [cceh/capitularia#17]
In Google Chrome funktioniert die Ansicht nicht richtig; nach dem Schritt "Handschriften anzeigen" erscheint eine statische Liste, mit der man nicht mehr weiterarbeiten kann. Google Chrome nicht benutzen? Oder lässt sich das mit einer kleinen Anpassung beheben?

**Comment by MarcelloPerathoner** [comment]
Funktioniert mit Chromium auf Linux tadellos.

Bitte Browser Cache leeren und nochmal versuchen: Ctrl + Shift + R

**Comment by laMischke** [comment]
@MarcelloPerathoner 

Rückmeldung von Herrn Ubl: Funktioniert jetzt auch bei ihm.
