### ISSUE TITLE
Unerklärlicher Fehler bei der Kollation von BK 139_1_inscriptio

### ISSUE THREAD

**Issue by laMischke** [cceh/capitularia#170]
@domtru @Capitularia-sk 

Das Kollationstool hängt sich auf, wenn BK.139_1_inscriptio kollationiert werden soll. Wenn ich es richtig sehe, muss der Fehler in der Datei selestat-bh-14 liegen, denn die Kollation funktioniert, wenn man nur diese Hs. weglässt. Ich finde dort aber keinen Fehler im Code ...

**Comment by Capitularia-sk** [comment]
Das könnte das gleiche Problem wie bei BK 192 c. 14 in Paris lat. 4628a (2. Kopie), Paris lat. 4631 (2. Kopie) und Paris lat. 10758 sein. In allen drei Fällen kann das Kollationstool das Kapitel in diesen Handschriften nicht anzeigen. Im Code kann ich aber keinen Fehler entdecken, aber die Gemeinsamkeit aller 4 Fälle besteht darin, dass jeweils ein span innerhabl eines /ab/ mittels prev/next mit einem kompletten /ab/ verklammert ist. 
Möglicherweise gibt es ein Problem, wenn prev/next nicht die gleichen Ebenen verbindet (d.h. nicht /ab/ zu /ab/ oder span zu span verlinken), sondern eine gemischte Verklammerung durchführen soll?

**Comment by domtru** [comment]
Gleicher Fall bei paris-bn-lat-4631 bei BK 193 c. 1
