### ISSUE TITLE
Anzeige 2. Kopie im Kollationstool

### ISSUE THREAD

**Issue by domtru** [cceh/capitularia#172]
@laMischke @Capitularia-sk 

Das Tool zeigt ein mit prev/next verbundenes Kapitel, das auf zwei abs aufgeteilt ist, trotzdem als 1. und 2. Kopie an, obwohl im Code alles brav miteinander verschaltet ist. Bei der ersten Kopie wird dann der durchgängige Text angezeigt, bei der 2. Kopie dann nur der Teil des zweiten ab. Die zweite Kopie kann in diesen Fällen also eigentlich weg. Betrifft: schaffhausen-sb-min-75 BK 191 c. 9; schaffhausen-sb-min-75 BK 193 c. 5; paris-bn-lat-4761-1-2 BK 193 c. 1.

**Comment by MarcelloPerathoner** [comment]
Überreste von früheren, fehlerhaften Durchläufen. Alles neu gemacht.
