### ISSUE TITLE
Falsche alphabetische Sortierung in Handschriftenliste

### ISSUE THREAD

**Issue by AlinaOs** [cceh/capitularia#176]
@Capitularia-sk @domtru @laMischke 

In der Handschriftenliste nach Signatur (https://capitularia.uni-koeln.de/mss/idno) ist die Handschrift Sélestat, Bibliothèque Humaniste, 14 (104) alphabetisch falsch einsortiert, nämlich ganz am Ende nach Stuttgart statt vorher nach Schaffhausen. Womöglich werden Buchstaben mit Akzenten nicht abgefangen (wie hier das é).

**Comment by MarcelloPerathoner** [comment]
Ist erstmal korrigiert.

Aber ein grundsätzliches Problem bleibt: daß ein Deutscher eine andere Sortierung erwartet als ein Franzose oder Engländer. (Ganz zu schweigen von den Differenzen Deutsch-Duden und Deutsch-Telefonbuch.) Dieses Problem können wir mit dem Mehrsprachen-Plugin nicht lösen. Wir müßten für Deutsch eine ganz andere Seite erzeugen als für Englisch, usw.

Jetzt ist eine Unicode-Sortierung nach deutscher Sprache voreingestellt.
