### ISSUE TITLE
Bug Handschriftenübersicht

### ISSUE THREAD

**Issue by laMischke** [cceh/capitularia#180]
@domtru @Capitularia-sk 

Die Handschriftenübersichtsseite "nach Signatur" (https://capitularia.uni-koeln.de/mss/idno/) lädt seit einigen Tagen nicht mehr (d.h. sie hat keinen Seiteninhalt).

**Comment by MarcelloPerathoner** [comment]
Die Datei ```wolfenbuettel-hab-helmst-254.xml``` enthielt ein paar Fehler. Habe ich jetzt korrigiert.

**Comment by laMischke** [comment]
@Capitularia-sk @domtru 

Jetzt funktioniert sie schon wieder nicht mehr ... möglicherweise neue Fehler in irgendeiner Datei?!

**Comment by MarcelloPerathoner** [comment]
Kommentare dürfen nicht an den Anfang der Datei.

failed to parse XML file file:/afs/rrz.uni-koeln.de/vol/www/projekt/capitularia/http/docs/cap/publ/mss/wolfenbuettel-hab-blankenb-130.xml: org.xml.sax.SAXParseException; systemId: file:/afs/rrz.uni-koeln.de/vol/www/projekt/capitularia/http/docs/cap/publ/mss/wolfenbuettel-hab-blankenb-130.xml; lineNumber: 8; columnNumber: 6; The processing instruction target matching "[xX][mM][lL]" is not allowed.
