### ISSUE TITLE
<note type="corr"> doesnt show a popup.

### ISSUE THREAD

**Issue by MarcelloPerathoner** [cceh/capitularia#187]
&lt;note type="corr"> doesnt show a popup in the  header section.

**Comment by MarcelloPerathoner** [comment]
Works for me. Test cases in: 
https://capitularia.uni-koeln.de/mss/london-bl-egerton-269/
https://capitularia.uni-koeln.de/mss/gotha-flb-memb-ii-189/
Please give an example where it doesn't work.

**Comment by domtru** [comment]
Funktioniert nicht bei https://capitularia.uni-koeln.de/mss/modena-bc-o-i-2/
