### ISSUE TITLE
Farbige Formatierungen in Fußnotentext

### ISSUE THREAD

**Issue by Capitularia-sk** [cceh/capitularia#19]
Aktuell wird mit rend="coloured" markierter Text (sei es mittels Attribut in einem &lt;ab&gt;, sei es direkt mittels hi-Element) im Obertext rot/orange angezeigt, im Fußnotentext dagegen unformatiert schwarz.

Lässt sich das ohne dramatischen Aufwand dahingehend ändern, dass der entsprechende Text überall gemäß seiner Kodierung formatiert erscheint? Separate hi-Elemente können auch innerhalb von add bzw. subst geschachtelt auftreten.

**Comment by MarcelloPerathoner** [comment]
Die Vorarbeiten sind geleistet. Allerdings finde ich keine relevante Stelle an der ich es testen könnte. Benötige eine Stelle als Beispiel.

**Comment by Capitularia-sk** [comment]
Zwei Beispiele zum Testen:
Berlin 1737 (direkt die ersten farbigen Absätze)
http://capitularia.uni-koeln.de/mss/berlin-sb-phill-1737/
Barcelona Ripoll 40 (die farbige Rubrik zu BK 190, mit der Anmerkungen zu "GENERALE")
http://capitularia.uni-koeln.de/mss/barcelona-aca-ripoll-40/

Wir haben gerade das Ganze nochmal ausgiebig diskutiert, hinsichtlich Einheitlichkeit und Abstimmung mit bereits vorhandenen Skriptanweisungen, die dadurch überflüssig würden. Folgendes wäre unsere Lieblingslösung:

(1) Jeder Text bzw. Buchstabe, sowohl im Obertext wie in den Fußnoten, erscheint in der Farbe, die ihm im Code implizit oder explizit zugeordnet ist (coloured/rot bzw. default/schwarz). Das bedeutet, dass auch eher banale Fußnoten, die nur eine Abkürzung dokumentieren, deren Zeichenbestand nun ggf. rot darstellen, wenn das entsprechende choice-Element im Obertext die Auflösung auch rot darstellen würde.
(2) Sofern ein <ab> nicht direkt ein rend enthält (was dann eigentlich immer nur coloured lauten sollte), wird der gesamte Text im <ab> schwarz dargestellt, mit rend="coloured" dann natürlich rot. Abweichungen für Buchstaben oder Worte innerhalb des <ab> können auftreten durch:
rend-Attribute in: <add> oder <del> oder <hi>. In solchen Fällen ersetzt die kleinräumigere Kodierung die global für den <ab> festgelegte Farbe.
(3) Das bedeutet vor allem Änderungen für die Fußnoten, aber z.T. auch im Obertext. Im Bsp. Barcelona Ripoll 40 ist z.B. die Ergänzung von "-LE" bei "GENERALE" als <add rend=default> innerhalb eines <ab rend="coloured"> kodiert, aber diese Kodierung wird nur durch einen Textzusatz in der Fußnote ("LE in Texttinte ergänzt") umgesetzt, die Buchstaben selbst erscheinen analog zum zugehörigen Wort in rot.
(4) Entsprechend können die bisher im Skript enthaltenen Anweisungen für die Umsetzung von rend-Atttributen durch Standardtext (mutmaßlich "in Texttinte" sowie "in [oder "mit"?] farbiger Tinte") entfallen, bzw. zu Anweisungen zur Farbgestaltung umgebaut werden.

**Comment by Capitularia-sk** [comment]
Ein komplexer Fall, bei dem die Farbdarstellung in der Fußnote noch nicht ganz klappt:
Bei 
http://capitularia.uni-koeln.de/mss/wolfenbuettel-hab-blankenb-130/
auf fol. 70v bei
"TITULUM · I · INCIPIUNT CAPITULA* QUE SUO TEMPORE* DOMNI HLOTHARIUS IMPERATORIS* OLONNA CONSTITUIT" 
sind Teile der farbigen Überschrift mit schwarzer Tinte korrigiert worden, u.a. die Wörter "suo tempore"; die automatische Fußnote lautet nun
"SUO TEMPORE von Hand B korr. aus [+]", wobei (korrekt) der Platzhalter [+] in rot, aber auch (inkorrekt) die Ergänzung "SUO TEMPORE" in rot dargestellt werden.

Der zugrundeliegende Code lautet (vereinfacht):
(ab type="meta-text" rend="coloured" xml:id="wolfenbuettel-hab-blankenb-130-70v-14")
 TITULUM . I . INCIPIUNT CAPITULA QUE (subst)
                    (del/)
                    (add hand="B" rend="default")SUO TEMPORE(/add)
                (/subst)
Die Information, dass "suo tempore" default ist, wird also für den Haupttext ausgewertet, aber in der Fußnote nicht auf den Inhalt von /add/ übertragen (del hingegen völlig korrekt entsprechend dem für den ganzen /ab/ geltenden rend=coloured dargestellt.

Noch komplizierter wird es beim folgenden Passus "HLOTHARIUS IMPERATORIS" und ebenso bei "CONSTITUIT". Dort sind jeweils nur Teile eines Wortes mit schwarzer Tinte korrigiert (das -US bei Hlotharius, das -IT m Wortende bei constituit).

Kodiert ist das z.B. so:

CONSTITU(subst)
                    (del/)
                    (add hand="B" rend="default")IT * (/add)
                (/subst)

Erneut ist der Haupttext korrekt. Die Fußnote hat "CONSTITUIT ˙ von Hand B korr. aus CONSTITU[+]", wobei jeweils alle Zeichen von Constituit / Constitu[+] rot sind, statt nur die letzten 2 Buchstaben von Constituit.

Es wirkt so, als würden rend-Angaben innerhalb eines add innerhalb von subst zwar für den Haupttext umgesetzt, aber entweder gar nicht für den Fußnotentext berücksichtigt, oder dort von einer etwaigen rend-Angabe im ab gleich wieder überlagert.
