### ISSUE TITLE
Standardformulierungen

### ISSUE THREAD

**Issue by domtru** [cceh/capitularia#198]
@laMischke @Capitularia-sk 

Zu unserer eigenen Übersicht und Kontrolle bitte eine Liste erstellen, mit welchen Formulierungen bzw. Zeichen die einzelnen xml-tags in den Fußnoten der HTML-Präsentation realisiert werden.

**Comment by MarcelloPerathoner** [comment]
Hier ist ein Diagramm der Zeichenketten und der tags, die sie aufrufen:

![test](https://user-images.githubusercontent.com/7013063/112432339-0f0f8c80-8d41-11eb-9ad0-146ce2747fe0.png)
