### ISSUE TITLE
Fehler im Kollationstool

### ISSUE THREAD

**Issue by laMischke** [cceh/capitularia#207]
@Capitularia-sk @domtru 

Das Kollationstool scheint nicht richtig zu arbeiten:
1) Die Hs. mailand-ba-o-55 erscheint nicht in der Auswahl der zu kollationierenden Textzeugen (Bsp.: BK 168 ist enthalten und wohl auch korrekt kodiert, wird aber nicht angezeigt).
2) Das Kapitular BK 164a wird zur Auswahl angezeigt, obwohl es seit Längerem aus der BK-Superstruktur verschwunden ist (auskommentiert); die Datei, in der das geändert wurde, liegt auf dem Server hier: /afs/rrz.uni-koeln.de/vol/www/projekt/capitularia/http/docs/cap/intern/Transkriptionen/BK_Text_Superstruktur/bk-textzeuge.xml.

**Comment by domtru** [comment]
Weiteres Problem: in der Hs. Cava 4 bei BK 164 c. 6: Das gibt es zweimal, aber im Tool wird nur eine Version angezeigt.

**Comment by MarcelloPerathoner** [comment]
164.6 in Cava ist ein Sonderfall in dem es zweimal direkt hintereinander vorkommt. Wiederholungen waren bisher immer durch mindestens ein `<milestone unit="capitulare">` getrennt. Man müßte also vor und hinter die zweite Kopie jeweils  ein `<milestone unit="capitulare" n="BK.164_2">` bzw. `<milestone unit="capitulare" n="BK.164">` setzen.
