### ISSUE TITLE
corresp mit Ansegis bei der Kollationierung ignorieren

### ISSUE THREAD

**Issue by laMischke** [cceh/capitularia#21]
@MarcelloPerathoner @domtru @Capitularia-sk @skheinen 

Wir haben die corresp-Werte in den abs nun systematisch um Ansegis erweitert, was i.d.R. zu zwei Werten führt. Die Ansegis-corresps sind aber irrelevant für die Kollationierung, weshalb wir keine milestones für spans gesetzt haben.
Daher bitte für das Kollationstool beachten: corresp-Werte, die "Ansegis" enthalten, bei der Kollationierung komplett ignorieren!

**Comment by MarcelloPerathoner** [comment]
@corresp-Attribute, die mehrere, durch Leerzeichen getrennte Werte enthalten, werden nun korrekt verarbeitet. Wenn mehr gewünscht ist, bitte ein genaues Beispiel mit Kapitular und corresp.
