### ISSUE TITLE
gap in abbr

### ISSUE THREAD

**Issue by domtru** [cceh/capitularia#214]
@laMischke @Capitularia-sk 

Momentan zeigt das Schema an, dass ein gap-Element innerhalb eines abbr-Elements nicht erlaubt ist. Es wäre aber doch hilfreich, wenn dies zugelassen wird. Das gap-Element (mit quantity-Angabe) sollte dann wie ein allein stehendes gap-Element mit Punkten in eckigen Klammern wiedergegeben werden (Anzahl der Punkte nach quantity-Angabe).

**Comment by MarcelloPerathoner** [comment]
Das Schema ist schon mal geändert. Gibt es eine Stelle, an der der Tatbestand vorkommt, damit ich die Übersetzung kontrollieren kann?

**Comment by domtru** [comment]
Bei der Hs. Paris Lat. 4788 bei BK 146 c. 1 gibt es den Fall, Skript scheint sehr gut zu funktionieren
