### ISSUE TITLE
Interpunktion

### ISSUE THREAD

**Issue by domtru** [cceh/capitularia#218]
@laMischke  @Capitularia-sk 

Bei der Datei canisius-1604 (publ/mss) handelt es sich um einen Druck. Da bei den Drucken ja die gleichen Transformationen laufen wie bei den Handschriften werden die Punkte mittig in der Zeile positioniert angezeigt. Das ist für Drucke natürlich nicht sinnvoll. Vor und nach den Interpunktionszeichen stehen Leerzeichen normalerweise. Das ist bei den Drucken nicht der Fall. Dort stehen Interpunktionszeichen ohne Leerzeichen direkt am Wort. In solchen Fällen wäre es schön, wenn die Punkte auch als normale Punkte ausgegeben werden.

**Comment by MarcelloPerathoner** [comment]
Die Transformation der Interpunktion kann nun wahlweise abgeschaltet werden. Dafür muß im XML `<body data-shortcuts="0">` gesetzt werden. Wenn es ein Merkmal gibt um Drucke von Manuskripten zu unterscheiden, dann werde ich es gerne einbauen, mir ist nur keines aufgefallen. Haben wir schon publizierte Drucke?

**Comment by domtru** [comment]
Vielen Dank! Wenn ich bei der Canisius-1604-Datei schaue, erscheinen die Punkte allerdings immer noch hochgestellt. Das sicherste Merkmal, um Handschriften von Drucken zu unterscheiden ist der Dateiname, der bei Drucken immer nur aus Name und Jahr besteht (canisius-1604, nauclerus-1514, pithou-1688). Vielleicht könnte das helfen?

**Comment by MarcelloPerathoner** [comment]
Bei mir sind die Punkte unten. Vielleicht mal den Browser-Cache leeren oder vielleicht war das Skript auf dem Server einfach noch nicht komplett durchgelaufen.
