### ISSUE TITLE
Wordpress "Handschrift des Monats" zeigt nur jüngste 10 Posts

### ISSUE THREAD

**Issue by Capitularia-sk** [cceh/capitularia#22]
Ein Problem, das wir auch schon einmal früher (bei der Zahl der angezeigten Suchergebnisse?) hatten: 
Navigiert man zu Materialien / Handschrift des Monats, so werden dort in der Sidebar 13 Einträge für die Kategorie "Handschrift des Monats" angekündigt. Unmittelbar zu sehen sind aber nur die letzten 10. Die fehlenden drei sind als Posts noch vorhanden, aber es gibt keine Schaltfläche o.ä., mit der die Ansicht von den ersten/jüngsten 10 auf die nächsten 10 Posts weitergeschaltet werden könnte.
Das Problem scheint allgemeiner zu sein, insofern auch die Kategorie "Fortschritt" 11 Posts enthalten soll, aber nur 10 anzeigt.

**Comment by Capitularia-sk** [comment]
Nur eine Kleinigkeit: 
Die neue Anzeige zum Weiterschalten ist noch nicht vollständig an unsere beiden Sprachversionen angepasst. "Seite" / "Page" ist zweisprachig, aber in beiden Sprachen heißt es dann "Next" (statt "Weiter" - oder so - und "Next"). Ließe sich das vielleicht noch anpassen?

**Comment by laMischke** [comment]
@MarcelloPerathoner @Capitularia-sk @domtru 
Bei dieser Aktion muss irgendwas versehentlich geändert worden sein: Alle Blogposts (z.B. http://capitularia.uni-koeln.de/blog/handschrift-des-monats-april-2017/) und die Seite, die eine Übersicht über die Blogposts einer Kategorie geben (z.B. http://capitularia.uni-koeln.de/blog/category/handschrift-des-monats/), haben jetzt die Seitenüberschrift "Suchergebnisse".
