### ISSUE TITLE
Handschriftenseiten: Abfrage nach identischen corresp Werten ohne next/prev

### ISSUE THREAD

**Issue by Capitularia-sk** [cceh/capitularia#221]
Etwa Ähnliches hatten wir vor einiger Zeit wohl schon mal, aber ein paar Konstellationen haben wir damals wohl verpasst oder nicht bedacht. 
In einer älteren Transkription war eine Rubrik in zwei getrennten /ab/ erfasst worden, d.h. zwei aufeinanderfolgende /ab/ hatten das gleiche corresp. In diesem Fall wurde aber vergessen, oder es war damals noch nicht Standard, die beiden /ab/ mittels next und prev zu verbinden. Das Kollationstool ignoriert in solchen Fällen ja den Inhalt des zweiten /ab/ komplett, wodurch sich ein irreführender Eindruck vom Textbestand einer Handschrift ergeben kann. 

Um alle Fälle, wo ein solches Problem versteckt sein kann aufzufinden, wäre es schön, wenn sich eine möglichst umfassende Abfrage durchführen ließe. Diese müsste idealiter Folgendes prüfen (da nicht ganz auszuschließen ist, dass sich zwischen zwei /ab/ mit dem gleichen corresp noch ein oder gar mehrere /ab/ mit anderen corresp Werten befinden):

(a) Bereich: Für jeden Abschnitt zwischen zwei milestone type="capitulare"-Elementen
(b) Darin: Kommt der erste (1..n) corresp Wert im Abschnitt noch ein zweites (drittes...) Mal vor?
(c) Wenn ja: Sind die beiden Stellen mittels next/next oder next/prev verknüpft?
(d) Wenn nein: Liste diese Stellen bzw. deren xml:id als manuell zu prüfende Problemfälle auf.

Vielleicht macht es Sinn, bei dieser Gelegenheit auch gleich zu überprüfen, ob in einer Handschriftendatei versehentlich mal bei zwei milestone type="capitulare" der gleiche Wert vorkommt. Grundsätzlich soll, wenn es mehrere Exemplare des gleichen Kapitulars in einer Handschrift gibt, jedes Exemplar mit einem eigenen milestone eingeleitet werden, dessen Wert hochgezählt wird (z.B. "BK 191", "BK 191_2", "BK.191_3"). Aber falls wir das irgendwo übersehen haben sollten, wäre es gut, das auch noch abzufangen, bevor deshalb ggf. weitere Textabschnitte im Kollationstool unsichtbar bleiben.

**Comment by MarcelloPerathoner** [comment]
[221.txt](https://github.com/cceh/capitularia/files/8632110/221.txt)

Bei inscriptio wurde das generell etwas laxer gehandhabt. Vielleicht sollte ich inscriptio noch herausfiltern?

**Comment by MarcelloPerathoner** [comment]
[221.txt](https://github.com/cceh/capitularia/files/8639824/221.txt)

Dasselbe nochmal mit Überprüfung ob @corresp mit dem milestone @n übereinstimmt.

**Comment by domtru** [comment]
Vielen Dank für die Abfragen! Wir haben das nun nachbearbeitet, bitte zur Nachkontrolle nochmal die letzte Abfrage (mit corresp/milestone n) durchlaufen lassen und Liste erstellen. Danke!

**Comment by MarcelloPerathoner** [comment]
Abfrage nochmal durchgelaufen: [221.txt](https://github.com/cceh/capitularia/files/8669929/221.txt)
