### ISSUE TITLE
Benedictus Levita

### ISSUE THREAD

**Issue by domtru** [cceh/capitularia#224]
@laMischke @Capitularia-sk 

Wir haben die milestones (type capitulare) zu Stücken von Benedictus Levita in den xml-Dateien nun so gestaltet: "Benedictus.Levita". In der Sidebar soll das nun als "Benedictus Levita" wiedergegeben werden. Die dazugehörigen Kapitel sollen dann analog zu den BK- oder Mordek-Stücken angezeigt werden in der Sidebar. Z.B. corresp="Benedictus.Levita.1_279" als "1,279" in der Sidebar unter "Benedictus Levita". Die corresps der Kapitel bitte auch ausgeben im Text der Transkription (klein und grau in eckigen Klammern wie üblich): "Benedictus.Levita.1_279" als "Benedictus Levita 1,279". Danke!

**Comment by MarcelloPerathoner** [comment]
Ist das in der Sidebar ok so?

![Screenshot from 2022-05-10 11-34-23](https://user-images.githubusercontent.com/7013063/167598933-e661a7aa-7c3f-4af8-b189-d0fe7bce5153.png)

**Comment by Capitularia-sk** [comment]
Ja, genau so haben wir uns das vorgestellt, Danke!
