### ISSUE TITLE
Impressum: Piwik Opt-out "Seite nicht gefunden"

### ISSUE THREAD

**Issue by Capitularia-sk** [cceh/capitularia#230]
Unten auf der Impressum-Seite
https://capitularia.uni-koeln.de/sitenotice/
lädt offenbar ein Service nicht mehr, mit dem Nutzer einer Registrierung (Besuchsauswertung) durch Piwik widersprechen können. Konkret scheint es Verbindungsprobleme mit "projects.cceh.uni-koeln.de" zu geben (siehe Screenshot). 
Seit wann das besteht, und ob es nur ein kurzfristiger Ausfall heute ist, kann ich nicht sagen. Aber könnte das möglicherweise mit der Umstellung auf den neuen Server zu tun haben?

![Capitularia_Piwik_opt-out](https://user-images.githubusercontent.com/25320474/180961527-e94a993c-46ac-426c-9608-48b530fd8a59.png)

@laMischke @domtru

**Comment by MarcelloPerathoner** [comment]
Geht wieder.
