### ISSUE TITLE
Umformung ueberblick_mordek.xml

### ISSUE THREAD

**Issue by domtru** [cceh/capitularia#233]
@Capitularia-sk @laMischke 

Die Datei ueberblick_mordek.xml ist momentan nicht TEI-konform, u.a., weil es das capit-Element nicht gibt. In der ganzen Datei erscheinen rote Fehler. Es wäre gut, wenn die Datei TEI-konform umgeformt werden könnte.

**Comment by MarcelloPerathoner** [comment]
Die gesamte Datei umzuformen und die Transformationen anzupassen ist ein ziemlicher Akt.  Vielleicht ist es einfacher nur ein Schema hinzuzufügen.  Ich habe jetzt ein Schema generiert und der Datei hinzugefügt. Kannst Du mal versuchen ob es so funktioniert?

**Comment by domtru** [comment]
Alles klar, das geht natürlich auch. Die Datei sieht gut aus, immerhin erkennt man nun Fehler direkt.
