### ISSUE TITLE
Verlinkung zwischen Handschriften

### ISSUE THREAD

**Issue by Capitularia-sk** [cceh/capitularia#241]
Manchmal wurde eine Handschrift im Laufe der Zeit in mehrere Bestandteile (= neue, heutige Handschriften) zerlegt. Dadurch kann es vorkommen, dass ein Kapitular in einer Handschrift anfängt und in einer anderen aufhört. Wir haben das in den Dateien so kodiert, dass Nutzer an der Stelle, wo der Text quasi springt, ein rotes Verweiszeichen angezeigt bekommt, das zugleich als Link in die jeweils andere Handschrift fungiert. Im ersten Teil eines solchen Textes steht das Verweiszeichen entsprechend immer am Ende eines /ab/ und damit auf der html-Seite am Ende eines Textabsatzes. Als Zeichen ist ein gefülltes rotes Dreieck verwendet, das "nach rechts" zeigt, also grob ähnlich einem ">". Im zweiten Teil, also dort, wo der Text fortgesetzt wird, steht die Kodierung am Beginn eines /ab/ und sollte im html dann korrespondierend am Beginn des fortsetzenden Textabsatz ein nach links weisendes gefülltes rotes Dreieck ("<") mit Link-Funktion haben.

Zwei Probleme / Bitten:

(1)
Die Verlinkung erfolgt in beiden Fällen nach dem folgenden Schema:
` <ref type="internal" subtype="mss" target="london-bl-egerton-269#london-bl-egerton-269-9r-1"/>`
("ausgehender" Link vom Ende des ersten Textabschnitts)
`<ref type="internal" subtype="mss" target="london-bl-egerton-2832#london-bl-egerton-2832-53v-6"/>`
(zurückverweisender Link vom Anfang des zweiten Textabschnitts)

Die Richtung des Verweises, und entsprechend die nötige Form des Verweiszeichens (nach rechts / nach links) lässt sich also nur daraus bestimmen, ob das ref-Element direkt auf ein öffnendes ab-Element folgt, oder direkt vor einem schließenden ab-Element steht. Aktuell funktioniert bei den 3 Fällen, die ich bisher gesichtet habe (von London Egerton 269 zu London Egerton 2832; von London Egerton 269 zu Paris lat. 7561; von Vatikan Reg. lat. 980 zu Vatikan Reg. lat. 1283a) der "ausgehende" Link (nach rechts) wie erwartet, aber beim zurückverweisenden Link wird statt eines Dreiecks ein roter Kasten mit der zweizeiligen Beschriftung (wenn ich richtig entziffere) "0F0 D91" angezeigt; der Kasten funktioniert trotzdem als Link, sieht aber eben nicht so aus wie erhofft;
Ein Beispiel hier (Fortsetzung von BK 139 c. 6):
https://capitularia.uni-koeln.de/mss/london-bl-egerton-269/#x-menu-d4e1017

Früher hat das unserer Erinnerung funktioniert, möglicherweise ist es also nur ein Problem mit einer Änderung im Zeichensatz / bei der Zeichenkodierung, ggf. in Folge eines WordPress-Updates oder einem Wechsel der Standardschriftart. Könntest Du bitte einmal schauen, ob sich die Ansicht wieder hübsch machen lässt?

(2)
Bei dieser Gelegenheit fiel uns auf, dass wir in einer Datei offenbar vergessen hatten, das nötige Gegenstück einer solchen Verlinkung einzufügen. Daher die Bitte, ob Du einmal alle Handschriftenseiten auf solche Links durchsuchen könntest und zwar speziell für alle Fälle, wo ggf. ein solches Link-Paar sonst noch unvollständig ist. Links auf Handschriftenseiten kommen in den Dateien häufig vor, aber die hier allein interessierende Art lässt sich daran erkennen, dass sie im target noch ein # (mit folgender xml-id) hat. 
Eine einfache Liste aller solcher Links müsste schon genügen, es dürften nur so wenige sein, dass sich die zusammengehörigen Paare (und entsprechend auch die verwaisten Links) schnell finden lassen.

**Comment by MarcelloPerathoner** [comment]
1) Das fehlende "Zurück"-Dreieck war nur ein Tippfehler. Geht jetzt wieder.

2) Ich habe folgende Verlinkungen gefunden:

```
Datei                          Link

ivrea-bc-xxxiv.xml             turin-bnu-fragment#turin-bnu-fragment-recto-2
turin-bnu-fragment.xml         ivrea-bc-xxxiv#ivrea-bc-xxxiv-167v-8

london-bl-egerton-269.xml      london-bl-egerton-2832#london-bl-egerton-2832-53v-6
london-bl-egerton-2832.xml     london-bl-egerton-269#london-bl-egerton-269-9r-1

london-bl-egerton-269.xml      paris-bn-lat-7561#paris-bn-lat-7561-29-1
paris-bn-lat-7561.xml          london-bl-egerton-269#london-bl-egerton-269-17v-2

vatikan-bav-reg-lat-1283a.xml  vatikan-bav-reg-lat-980#vatikan-bav-reg-lat-980-14v-12
vatikan-bav-reg-lat-980.xml    vatikan-bav-reg-lat-1283a#vatikan-bav-reg-lat-1283a-66r-1

montecassino-ada-175.xml       #cava-dei-tirreni-bdb-4
muenchen-bsb-lat-29555-1.xml   #muenchen-bsb-lat-29555_sn2
schaffhausen-sb-min-75.xml     #schaffhausen-sb-min-75_toc_thegan
schaffhausen-sb-min-75.xml     #schaffhausen-sb-min-75_toc_thegan
vatikan-bav-reg-lat-1283a.xml  vatikan-bav-reg-lat-980#editorial-preface
```
