### ISSUE TITLE
URL verursacht Fehler im xml-Dokument

### ISSUE THREAD

**Issue by laMischke** [cceh/capitularia#243]
@Capitularia-sk 

Nach Einfügen eines Links zu einem neuen Online-Digitalisat in der Datei troyes-bm-1979 wird die Datei invalide, weil innerhalb der URL (Permalink) ein "p=" vorkommt, das offenbar als Teil einer xml-Syntax "missverstanden" wird.
Wie kann man das umgehen?

**Comment by MarcelloPerathoner** [comment]
Sorry, habe das Issue ein wenig verschlafen.

Es handelt sich hier um das `&` Zeichen, das in XML als `&amp;` geschrieben werden muß, also `&amp;p=*`. Ich habe das in cap/publ schon geändert.

Der Link zeigt jetzt: "Digitalisat verfügbar bei Médiathèque Jacques-Chirac". Wenn das nicht in Odnung ist, bitte nochmal melden.
