### ISSUE TITLE
Volltextsuche auf der Homepage: Frage zur Funktionsweise

### ISSUE THREAD

**Issue by Capitularia-sk** [cceh/capitularia#246]
Wenn man auf der Homepage als eingeloggter Nutzer z.B. den Suchausdruck "de pace ecclesiarum" eingibt, erhält man als Ergebnis angezeigt:

> Ihre Suche nach: "de pace ecclesiarum" ergab 2 Treffer.
> 
> Heiligenkreuz, Stiftsbibliothek, 217
> 
>    Hansen, Die Rechtscorpora, S. 41-58). 182v-183r Drei Kanones von Mainz, Arles und Tours (a. 813) De pace ecclesiarum, wie in Cod. >    Berlin Lat. qu. 931, fol. 89r (und Kopie Cod. München Lat. 6360). 183r-184r
>
> Private: Heiligenkreuz, Stiftsbibliothek, 217
> 
>    Hansen, Die Rechtscorpora, S. 41-58). 182v-183r Drei Kanones von Mainz, Arles und Tours (a. 813) De pace ecclesiarum, wie in Cod. >    Berlin Lat. qu. 931, fol. 89r (und Kopie Cod. München Lat. 6360). 183r-184r
>
Nicht eingeloggte Nutzer sehen hingegen nur den ersten dieser beiden Treffer.
Wie arbeitet der Suchprozess bei WordPress hier? Im Prinzip gibt es doch, wäre unsere Vorstellung, nur eine Datei, die in diesem Fall den Status "veröffentlicht" (public) hat. Und als zweite Frage: Ließe sich das grundsätzlich anpassen, oder ist das fest in WordPress selbst verankert?

**Comment by MarcelloPerathoner** [comment]
In diesem Fall (und in anderen) gibt es tatsächlich zwei Dateien, eine ohne und eine mit Kommentaren. Die Datei mit Kommentaren ist natürlich nur intern sichtbar.  Falls die Dateien mit Kommentaren nicht mehr benötigt werden, können sie im Seitengenerator abgestellt werden.

**Comment by Capitularia-sk** [comment]
Ok, aktuell benötigen wir diese Dateien "mit Kommentaren" tatsächlich nicht mehr. Möglicherweise werden wir einzelne in Zukunft wieder brauchen zur Vorbereitung einer Archivreise, aber das wäre punktuell und zeitlich begrenzt; dazu müssen wir nicht, wie jetzt, permanent 344 Seiten vorhalten.
"Abstellen" heißt, wir können die derzeit dort privat veröffentlichten Dateien einfach alle "un-veröffentlichen" (womit alles den gleichen Status wie aktuell die Datei "barcelona-bc-945" bekommt), und damit tauchen sie künftig nicht mehr unter den Suchergebnissen auf, richtig? Und falls wir später eine davon erneut brauchen, generieren wir sie wieder im Seitengenerator?

**Comment by MarcelloPerathoner** [comment]
Ich habe alle Dateien "mit Kommentaren" un-veröffentlicht. Falls wieder gebraucht einfach neu "privat veröffentlichen".
