### ISSUE TITLE
Schema anpassen: Beschreibung in figDesc / Leerzeichen nach Platzhaltern

### ISSUE THREAD

**Issue by laMischke** [cceh/capitularia#252]
@Capitularia-sk 

Laut Schema soll im Text innerhalb von figDesc, wie in den Transkriptionen, vor und nach einem Platzhalter ein Leerzeichen stehen. 
Bitte ändern: In figDesc können Platzhalter auch ohne Leerzeichen stehen.

**Comment by MarcelloPerathoner** [comment]
Das verstehe ich nicht ganz. In figDesc kann beliebiger Text eingetragen werden. Oder meinst du die Regel, daß figure immer ein figDesc _und_ ein graphic enthalten muß?

Kannst du mir bitte ein Beispiel geben das nicht validiert, aber validieren sollte?

**Comment by laMischke** [comment]
Ich habe mich auch gewundert - in der Datei, die ich gerade bearbeite (Kopie hier: /cap/intern/InArbeit/modena-bc-o-i-2_KOPIE.xml) kommt jedenfalls bei figDesc die (gelbe) Fehlermeldung: "Auf Platzhalter folgt kein Leerzeichen."
