### ISSUE TITLE
Fehlermeldung bei Hss.-Seitenaufruf

### ISSUE THREAD

**Issue by laMischke** [cceh/capitularia#254]
@Capitularia-sk @MarcelloPerathoner 

Wenn man die Seite https://capitularia.uni-koeln.de/mss/gotha-flb-memb-i-84/ aufruft, gibt es eine Fehlermeldung ("There has been a critical error on this website."). Einen Fehler in der XML-Datei kann ich nicht entdecken; betroffen ist offenbar nur diese Seite.

**Comment by Capitularia-sk** [comment]
Das gleiche Problem besteht auch mit
[](https://capitularia.uni-koeln.de/mss/gotha-flb-memb-i-85/)

**Comment by MarcelloPerathoner** [comment]
Geht jetzt wieder.
