### ISSUE TITLE
Kollationstool: Probleme bei vielen corresp-Werten

### ISSUE THREAD

**Issue by laMischke** [cceh/capitularia#27]
@MarcelloPerathoner @Capitularia-sk @domtru @skheinen 

Beim Versuch, den Text von BK 141 c. 29 in allen Handschriften zu vergleichen, wurde bei drei Hss. (ivrea-bc-xxxiv, paris-bn-lat-4280a, paris-bn-lat-4788) der Text des gesamten Kapitulars verglichen. In allen drei Hss. sind die einzelnen Kapitel von BK 141 optisch nicht als solche erkennbar, weshalb sie in einem einzigen ab stehen, der eine sehr große Anzahl von corresp-Werten hat. C. 29 ist das letzte Kapitel, es steht also bei den corresp-Werten an letzter Stelle. - Die Abgrenzung der einzelnen milestones type="span" scheint aber korrekt zu sein, daran liegt es offenbar nicht. - Wenn man den Test mit einem anderen Kapitel wiederholt, variiert das Ergebnis; bei c. 25 z.B. kommen weitere Hss. dazu, bei denen das gesamte Kapitular verglichen wird (plus montpellier-biu-h-136, paris-bn-lat-2718). Wahrscheinlich liegt es an der ungewöhnlich großen Zahl von corresp-Werten, aber sicher ist das nicht.

**Comment by MarcelloPerathoner** [comment]
Das liegt am &lt;ab @corresp="... BK.141_29">. Dadurch wird das gesamte ab dem BK.141_29 zugeordnet.

Wenn ein ab in milestones unterteilt ist, solllte das ab keinen @corresp bekommen. Wenigstens nicht für das Kollationstool. Ob ihr den @corresp auf ab noch für andere Zwecke benötigt, weiß ich jetzt nicht.

**Comment by laMischke** [comment]
@MarcelloPerathoner @Capitularia-sk @domtru @skheinen 

Wir brauchen die corresp-Werte im ab, weil sie für die HTML-Präsentation verwendet werden.

Daher wie vereinbart: Bei ab type="text" mit mehreren Werten im corresp (Ausnahme: "Ansegis") nach den Werten der corresps in den milestone type="span" suchen, die in diesem ab folgen.
(Alle im corresp des ab aufgelisteten Werte - mit Ausnahme der "Ansegis" enthaltenden - müssen einzeln in den milestones im selben ab enthalten sein, ansonsten gibt es einen Fehler in der Codierung!)

**Comment by Capitularia-sk** [comment]
Oder evtl. einfacher: Wenn ein /ab/ ein Element milestone type="span" enthält (es werden jeweils mindestens 2 milestones sein), sollten die corresp-Werte in /ab/ selbst ignoriert werden und lediglich die corresp-Werte innerhalb der enthaltenen milestone-Elemente berücksichtigt werden.
Dann braucht es keine Sonderregeln für corresp mit Ansegis als zweitem Wert.
