### ISSUE TITLE
Suche im Wiki

### ISSUE THREAD

**Issue by laMischke** [cceh/capitularia#31]
@Capitularia-sk @domtru @skheinen 

Kann man das Projekt-Wiki (http://capitularia.uni-koeln.de/wp-admin/admin.php?page=wp-help-documents) gezielt nach bestimmten Begriffen durchsuchen (ohne dafür alle WP-Seiten durchsuchen zu lassen)?

**Comment by MarcelloPerathoner** [comment]
Geht jetzt. Man suche z.B. nach "wiki:Ortsregister". (Zuerst einloggen.)
