### ISSUE TITLE
Responsivität der WP-Seite

### ISSUE THREAD

**Issue by laMischke** [cceh/capitularia#32]
@Capitularia-sk @domtru @skheinen 

Wie vereinbart, bitte zunächst testen, ob mit relativ wenig Zeitaufwand eine "unschöne" Responsivität der Seite (Gesamtansicht mit Bildlaufleisten oben-unten und rechts-links) umsetzbar ist.

Am 22. Juni (Treffen mit Herrn Ubl) klären wir dann, ob das ausreicht oder nicht und was konkret gewünscht wird.

**Comment by laMischke** [comment]
@Capitularia-sk @domtru @skheinen 

Eine Kleinigkeit, die nicht klappt: Wenn man die Breite des Fensters stark verkleinert, ragen die Kreuzchen eines "langen" del (hier: quantity="60") in die Sidebar hinein, weil kein Zeilenumbruch stattfindet (Bsp.: xml:id="paris-bn-nouv-acq-lat-204-24v-2"). Kann man das anpassen?

**Comment by laMischke** [comment]
@Capitularia-sk @domtru @skheinen 

Noch etwas: Kann man die erste Zeile der ausgewählten Ansicht verankern, wenn man die Fenstergröße verändert? Jetzt "springt" die Ansicht und man muss scrollen, bis man die Textstelle wiedergefunden hat.

**Comment by Capitularia-sk** [comment]
Eine weitere Kleinigkeit aus der Bibliographie, dort in der Sidebar: 
Während die Überschriften (jedenfalls bei "Editionen und Übersetzungen") beim Zusammenschieben des Fensters in eine neue Zeile umbrechen, bleiben die verlinkten Buchstaben zum Springen (nach "Titel, die mit G anfangen" etc.) fest in ihrer ursprünglichen Abfolge. Beim Zusammenschieben kommt es entsprechend dazu, dass diese Buchstaben anfangen, sich gegenseitig zu überlappen, was das Anklicken eines bestimmten Buchstabens zu einer sportlichen Herausforderung machen kann.
Lässt sich das so ändern, dass das Alphabet bis zu einem gewissen Grad permanent umbricht und den Abstand zwischen den einzelnen Buchstaben nicht unter einen bestimmten Wert fallen lässt?

**Comment by MarcelloPerathoner** [comment]
Daß der Browser "springt" wenn man die Fenstergröße verändert, läßt sich leider nicht vermeiden.
