### ISSUE TITLE
Anzeige der haltenden Bibliothek bei öffentlich verfügbaren Digitalisaten

### ISSUE THREAD

**Issue by Capitularia-sk** [cceh/capitularia#33]
Sofern es ein öffentlich zugängliches Digitalisat gibt, wird der Link dazu in /facsimile/ eingetragen und automatisch zur Ausgabe verarbeitet (z.B. bei Hss. aus Paris: "Digitalisat verfügbar bei BnF"). Das funktioniert allerdings nur, wenn irgendwo hinterlegt ist, welchen Bibliothek- oder Archivnamen das Skript anzeigen soll, wenn eine bestimmte Zeichenfolge im Link enthalten ist. Ist das noch nicht geschehen, wird nur "Digitalisat verfügbar bei" gefolgt vom Symbol für einen externen Link angezeigt.

Beispiel: Ivrea 34 (ivrea-bc-xxxiv)

  ```
 <facsimile>
      <graphic url="http://gutenberg.beic.it/webclient/DeliveryManager?pid=10301007"/>
   </facsimile>
```

Zwei Probleme:
(1) In welcher Datei (xsl?) müssen wir diese Angaben wie eintragen?
(2) Es gibt derzeit offenbar mehrdeutige Einträge, d.h. eine Zeichenfolge kann in Links verschiedener Bibliotheken enthalten sein. Das führt zu irrigen Anzeigen wie z.B. bei der Hs. Kopenhagen, bei der es heißt: "Digitalisat verfügbar bei Manus online". Tatsächlich ist Manus online eine ganz andere Seite, die aber hier mutmaßlich irrig zugeordnet wurde, weil der Kopenhagener Link die Zeichenfolge "manus" enthält.

**Comment by domtru** [comment]
Wenn ich recht sehe, müssen wir das in der base_variables.xsl machen, die auf dem Server liegt. Wenn das richtig ist, dann können wir das in Zukunft selbst machen. Ich habe es mal testweise für Ivrea gemacht, es funktioniert!

**Comment by MarcelloPerathoner** [comment]
Die Schlüsselwörter werden in der base_variables.xsl eingetragen. Man soll diese Datei aber nicht auf dem Server editieren, da sie dann immer wieder von der "offiziellen" Datei auf github überschrieben wird. Die Änderungen bitte mir mitteilen, damit ich sie einpflegen kann. Habe das für die "mehrdeutigen" Einträge schon gemacht.

**Comment by domtru** [comment]
Bei der Handschrift Bamberg Can. 12 wird gar keine Institution beim Digitalisat angezeigt. Dies bitte nachtragen (Staatsbibliothek Bamberg)!
