### ISSUE TITLE
Druckausgabe: Weitere Anpassungswünsche

### ISSUE THREAD

**Issue by laMischke** [cceh/capitularia#35]
@Capitularia-sk @domtru @skheinen 

Beim letzten Ausdrucken einer Datei sind uns einige kleine "Fehler" aufgefallen, die vorher nicht da waren:
- In der Druckausgabe der Handschriftenseiten erscheint jetzt immer ein "( \ )" nach dem Capitularia-Logo
- Hochgestellte Zahlen in den automatisch generierten Anmerkungen werden nun immer kursiv ausgegeben (z.B. statu`mod`t`/mod`um - FN: t2 korr.(?); dabei soll das t kursiv sein, aber die 2 hochgestellt und **nicht** kursiv)
- Nach den `cb`s werden nun immer die Linkadressen der entsprechenden Digitalisate auf dem Bildserver angezeigt, wo diese automatisch verlinkt werden können

- Und noch ein Phänomen, das auch vorher schon dagewesen sein muss, uns aber erst jetzt als unerwünscht aufgefallen ist:
Wenn sich ein Kapitel über mehrere `ab`s erstreckt (z.B. in paris-bn-lat-4628a: BK.141_7, auf vier abs aufgeteilt), wird jeder ab (jeweils nur ein Satz ...) auf einer eigenen Seite ausgedruckt. Wünschenswert wäre, wenn nicht ein ab auf einer Seite, sondern ein Kapitel auf einer Seite stehen würde. (Gilt nicht nur für diesen Fall, sondern generell.)

**Comment by MarcelloPerathoner** [comment]
Bei Punkt 4 wird die BK-Nr. noch mehrmals ausgegeben. Kann das so bleiben?

**Comment by Capitularia-sk** [comment]
zu (4) mehrfache BK-Nr.: 
Gute Frage. Müssen wir hier nochmal überlegen. Finde ich erstmal nicht so störend. Allerdings werden ja auch etwaige Fußnoten jeweils zwischen die einzelnen /ab/ eines Kapitels geschoben, z.B. wieder bei der Hs. Paris 4628a: bei BK 141 c. 15. Das ist schon ein etwas gewöhnungsbedürftiger Anblick. 

zu (3) Linkadressen nach /cb/:
Das Problem (also, dass der Link ausgedruckt wird, anstatt vollständig ausgeblendet / im Ausdruck entfernt zu sein) scheint immer noch zu bestehen, wenn ich richtig sehe. 

zu (2) automatisch generierte hochgestellte Zahlen:
Ergänzend sind die Zahlen auch zu weit hochgestellt, so dass sie nicht halb in den Zeilenzwischenraum hineinragen, sondern komplett zwischen den Zeilen schweben. Beispiel Paris 4628a bei BK 140 c. 6.

zu (1): Der "(/)" nach dem Logo ist noch immer sichtbar (ein Produkt des nicht mehr angezeigten waagerechten Trennstrichs zwischen Logo und Seitentitel?), jedenfalls wenn ich die Druckvorschau bei Firefox aufrufe.

**Comment by Capitularia-sk** [comment]
Kleine Korrektur: 
Ich hatte Paris 4628a zwar frisch geladen, aber trotzdem zuerst noch den alten Zustand bzgl. (1) und (3) in der Druckvorschau angezeigt bekommen. Erst ein Neuladen der Seite auf Hinweis von Dominik hat mir jetzt die aktuelle Version ohne Probleme bei (1) und (3) angezeigt.

**Comment by MarcelloPerathoner** [comment]
2) geht jetzt und auch bei 4) werden die Fußnoten am Ende der Seite angezeigt.

**Comment by laMischke** [comment]
@Capitularia-sk @domtru @skheinen 

Zu dem o.g. Punkt 4 (beim Ausdruck nicht ein ab, sondern ein Kapitel pro Seite) noch ein Nachtrag:

Als Folge aus dieser Anpassung fehlen nun die Trennstriche zweischen den einzelnen abs in der HTML-Ansicht (Bsp.: http://capitularia.uni-koeln.de/mss/paris-bn-lat-4628/, BK 141 c. 12, aufgeteilt auf XI bis [X]IIII). Dort wäre es aber wichtig, die Trennung der einzelnen abs zu sehen - kann man das entkoppeln? Also Trennstriche zwischen den abs in der HTML-Ansicht wie vorher, aber trotzdem beim Ausdruck die zu einem Kapitel gehörigen abs zusammen auf eine Seite packen?
