### ISSUE TITLE
Verlinkungen zur BSB München

### ISSUE THREAD

**Issue by laMischke** [cceh/capitularia#45]
@Capitularia-sk @domtru @skheinen 

Bei Verlinkungen zu Online-Digitalisaten der BSB-München erscheint "BSB München" als Anker für den Link bei einigen Dateien (Bsp.: muenchen-bsb-lat-19416: graphic url="http://daten.digitale-sammlungen.de/bsb00017795/image_1"), bei anderen nicht:
Bsp.: muenchen-bsb-lat-29555-1: graphic url="http://daten.digitale-sammlungen.de/~db/0008/bsb00080501/images/.

P.S.: Es funktioniert auch nicht, wenn man die Linkadresse in derselben Form wie beim ersten Beispiel angibt: graphic url="http://daten.digitale-sammlungen.de/bsb00080501/image_1".

**Comment by domtru** [comment]
@MarcelloPerathoner   @laMischke 
In der base_variables.xsl steht für die BSB München als key "bsb-muenchen". Die Links dahin beinhalten diese Kennung aber nicht, sondern haben immer "daten.digitale-sammlungen" als key. Bitte entsprechend anpassen!

**Comment by domtru** [comment]
@MarcelloPerathoner
Eine Verwirrung gibt es auch bei den Digitalisaten der Biblioteca Apostolica Vaticana. In der HTML-Präsentation erscheint mal "Digitalisat verfügbar bei BAV", mal "Digitalisat verfügbar bei DVL". Bitte einheitlich zu BAV ändern!

**Comment by domtru** [comment]
@MarcelloPerathoner Bei der Handschrift Darmstadt, Hessische Landes- und Hochschulbibliothek, 231 wird in der HTML-Präsentation unter "Digitalisat verfügbar bei" nur der Pfeil ohne Nennung des Ziels angezeigt. Die PURL hat folgenden Inhalt: "tudigit.ulb.tu-darmstadt.de". Als Text sollte dort "ULB Darmstadt" erscheinen.
