### ISSUE TITLE
Vorbemerkung: kursiv/recte umkehren

### ISSUE THREAD

**Issue by laMischke** [cceh/capitularia#46]
@Capitularia-sk @domtru  @skheinen 

Eine kleine Änderung, um die editorische Vorbemerkung dem Format der Anmerkungstexte anzupassen:
In `front`/
`div type="mshist", "scribe", "letters", "structure", "annotations", "other", "abbreviations", "punctuation"`
den Text **recte** (statt wie bisher kursiv) setzen und die Teile **innerhalb von `mentioned` kursiv**.

**Comment by laMischke** [comment]
@Capitularia-sk @domtru @skheinen

Sorry, das bezog sich auf die Anmerkungen, **NICHT** auf die Vorbemerkung: In der Vorbemerkung soll alles so bleiben, wie es ist, aber **im Text der Anmerkungen** sollen **Zitate aus dem Text recte** gesetzt werden, der Rest **_kursiv_** - also genau umgekehrt wie bisher.

**Comment by MarcelloPerathoner** [comment]
Es gibt in den Anmerkungen einige Stellen, die mit &lt;hi rend="italic"&gt; gekennzeichent sind. Diese werden nun nicht mehr sichtbar hervorgehoben sein. z.B. suche "trigibach" in wolfenbuettel-hab-blankenb-130.

**Comment by laMischke** [comment]
@Capitularia-sk @domtru @skheinen 

Wie eben besprochen: mit "Anmerkungen" waren die notes bzw. automatisch generierten Fußnoten im Transkriptionstext gemeint; d.h., alles was im `body` steht bzw. in den Pop-Ups der HTML-Version erscheint - das Beispiel mit "trigibach" steht im `header`.
