### ISSUE TITLE
@corresp mit "_prolog", "_epilog"

### ISSUE THREAD

**Issue by laMischke** [cceh/capitularia#49]
@Capitularia-sk @domtru @skheinen 

In der HTML-Ansicht werden die corresp-Attribute, die "_prolog" oder "_epilog" enthalten, genauso verarbeitet wie die mit Angabe von "BK-Nr._Kapitel", was zu der unsinnigen Formulierung "BK 164 c. epilog" führt.

Daher bitte alle corresp-Werte, die entweder "prolog" oder "epilog" enthalten, nach folgendem Muster anzeigen:
"BK XY Prolog", "BK xy Epilog" (also ohne "c.", erster Buchstabe E/P groß geschrieben)

**Comment by MarcelloPerathoner** [comment]
_praefatio noch hinzugefügt.
