### ISSUE TITLE
Kollationstool: Anzeige im Dropdownmenü

### ISSUE THREAD

**Issue by Capitularia-sk** [cceh/capitularia#5]
Auf der Suche nach überholten corresp-Elementen in Handschriftendateien mittels der Übersicht im Kollationstool fiel mir auf, dass dort im Dropdownmenü (in dem alle vorhandenen corresp-Elemente zu einem Kapitular angezeigt werden) manchmal Einträge zu finden sind, die in der aktuellen Dateifassung im publ/mss Ordner bereits nicht mehr vorhanden sind.

Beispiel: 
Laut Kollationstool sollte in der Datei "vatikan-bav-chigi-f-iv-75" ein (obsoletes) corresp auf "BK.162_incipit" stehen. Die Fassung im mss-Ordner enthält aber kein solches corresp.

Frage: 
Woher bezieht die Dropdownliste ihre Einträge - direkt "live" aus den Dateien im mss-Ordner, oder aus einem (älteren?) Register, oder gar aus älteren, anderswo hinterlegten Dateifassungen? Und wie kann man die Liste entsprechend auf den aktuellen Stand bringen?

**Comment by MarcelloPerathoner** [comment]
Die Einträge kommen aus der Datenbank. Oft haben wir ein- und dieselbe XML-Datei auf mehreren Seiten "eingehängt". z.B. jetzt bei den Seiten mit Kommentar. Die Datenbank wird aber nur aktualisiert wenn die XML-Datei sich ändert und danach die Seite aufgerufen wird. Das ist die Konsequenz daraus, daß wir ein Web-Projekt haben, und somit alle Prozesse von Seitenaufrufen gestartet werden müssen.
