### ISSUE TITLE
note type="msDetail": aus allen Dateien entfernen

### ISSUE THREAD

**Issue by laMischke** [cceh/capitularia#53]
@Capitularia-sk @domtru @skheinen 

Im `header` unserer Hss.-Dateien finden sich `note`s type="msDetail", die alle leere Elemente sein müssten und komplett entfernt werden sollen, da wir sie nicht mehr brauchen.

Bitte vorher prüfen, ob sich darunter nicht doch ein nicht-leeres Element findet; die darin enthaltene Information müssten wir dann woanders unterbringen.

**Comment by MarcelloPerathoner** [comment]
6 Fundstellen in 3 Manuskripten:

**muenchen-bsb-inc-s-a-26m.xml**

[Zur Einordnung des Fragments in die von Seeliger
                           vorgeschlagene Reihenfolge innerhalb der Benediktbeurer Hs. siehe die
                           Inhaltsbeschreibung bei München, Bayerische

**muenchen-bsb-lat-29555-1.xml**

[Nach diesem Blatt ist dem Vorschlag Seeligers
                           entsprechend einzuordnen: München, Universitätsbibliothek,
                              Einzelblatt 1]
[Nach diesem Blatt sind dem Vorschlag Seeligers
                           entsprechend einzuordnen: München, Universitätsbibliothek, vier
[Nach diesem Doppelblatt ist dem Vorschlag Seeligers
                           entsprechend einzuordnen: München, Bayerische
                              Staatsbibliothek, Inc. s. a. 26m, Einzelblatt]
[Nach diesem Blatt ist dem Vorschlag Seeligers
                           entsprechend einzuordnen: München, Universitätsbibliothek,
                              Einzelblatt 4]

**muenchen-ub-fragmente.xml**

[Zur Einordnung der Fragmente in die von Seeliger
                           vorgeschlagene Reihenfolge innerhalb der Benediktbeurer Hs. siehe die
                           Beschreibung des Inhalts von München, Bayerische

**Comment by laMischke** [comment]
@Capitularia-sk @domtru @skheinen 

OK, die Informationen brauchen wir noch - aber wir können dafür auch `note type="annotation"` nehmen, das verwenden wir auch schon bei den Kapitularienseiten.

Bitte alle leeren `note type="msDetail"` löschen;
bei den oben angeführten sechs Fällen: `note type="msDetail"` umbenennen in `note type="annotation"`;
diese genauso anzeigen wie jetzt die `note type="msDetail"`.

**Comment by MarcelloPerathoner** [comment]
&lt;note msDetail&gt; ist in allen publizierten Dateien entfernt.
