### ISSUE TITLE
Sonderzeichen für römische Zahlzeichen mit übergestellten Strichen

### ISSUE THREAD

**Issue by laMischke** [cceh/capitularia#54]
@Capitularia-sk @domtru @skheinen 

Problem: für einige Zahlzeichen, z.B. V mit übergestelltem waagerechtem Strich, gibt es kein Unicodezeichen.
Kann man eine Kombination aus zwei Unicode-Elementen dafür verwenden? 
Müsste man in den gängien Browsern testen.

Beim deutschen Textarchiv findet folgendes Zeichen für einen Kürzungsstrich Anwendung: http://www.deutschestextarchiv.de/doku/basisformat/trNasalstrich.html - vielleicht kann man damit etwas anfangen?

**Comment by domtru** [comment]
Das Beispiel des Deutschen Textarchivs ist eine Tilde, was tatsächlich bei uns funktioniert auf der Seite auch richtig dargestellt wird. Tauscht man den Tilden-Code gegen den Makron-Code aus, geht es leider nicht. Was aber funktioniert ist, wenn man `&#298;` ins XML eingibt, dann wird korrekt I mit Makron ausgegeben, allerdings funktioniert das nicht mit dem V.

**Comment by MarcelloPerathoner** [comment]
Testseite: http://capitularia.uni-koeln.de/test/test-combining-macro/
Mit Chrome sieht es bei mir gut aus, mit Firefox ist der Strich zu tief.

**Comment by laMischke** [comment]
@Capitularia-sk @domtru @skheinen 

Wir haben noch einen kreativen Vorschlag: Kann man das V mit Überstrich darstellen, indem man ein Lamda (https://unicode-table.com/de/039B/) mit Unterstrich (https://unicode-table.com/de/005F/) kombiniert und um 180 Grad dreht/auf den Kopf stellt?

**Comment by domtru** [comment]
Folgende Kombination aus verschiedenen Codes kommt dem gewünschten Zeichen zumindest nahe: `&#x305;&#86;&#x305`; Was sollte man am besten nehmen, damit auch eine langfristige Verarbeitung gesichert ist?

**Comment by laMischke** [comment]
@Capitularia-sk @domtru @skheinen 

Und wie sollen wir die Zeichen in Oxygen eingeben: als Sonderzeichen oder mit dem HTML-Code von Unicode?

**Comment by domtru** [comment]
Vorläufiges Vorgehen: Zahl wird ohne Sonderzeichen geschrieben, nur mit den normalen Buchstaben, eine note erklärt den Sachverhalt und löst zugleich den Zahlenwert auf
