### ISSUE TITLE
Digitalisate BN Paris

### ISSUE THREAD

**Issue by domtru** [cceh/capitularia#55]
Die Digitalisate der Bibliotheque Nationale in Paris werden auf den Handschriftenseiten als "Digitalisat verfügbar bei BnF" angezeigt. Das BnF bitte in "BN" ändern.

**Comment by laMischke** [comment]
@Capitularia-sk @domtru @skheinen 

Sorry, auch hier wieder eine Änderung ... da tatsächlich nicht alle Handschriften, von denen Digitalisate auf Gallica zu finden sind (URLs beginnen mit http://gallica.bnf.fr[...]), sich auch in der BnF befinden, muss die Formulierung lauten "Digitalisat verfügbar bei Gallica".
