### ISSUE TITLE
Neuer Tooltip für ref subtype="Werminghoff"

### ISSUE THREAD

**Issue by laMischke** [cceh/capitularia#59]
@Capitularia-sk @domtru @skheinen 

Bitte einen neuen Tooltip anlegen für Verlinkungen zur Edition von Werminghoff aus den Kapitularienseiten (`ref type="external" subtype="Werminghoff"`), Text:
"Zur Edition von Werminghoff (dMGH)".

**Comment by MarcelloPerathoner** [comment]
Zu welcher URL soll das führen?

**Comment by laMischke** [comment]
@Capitularia-sk @domtru @skheinen 

Zu target="http://www.mgh.de/dmgh/resolving/MGH_Conc._2,1_[Seitenzahl]" bzw. "(...)/MGH_Conc._2,1_[Seitenzahl]".

Ich sehe gerade, dass wir bei einigen älteren Kapitularienseiten an diesen Stellen noch den subtype="dmgh" vergeben haben; da kann das ja nicht funktionieren ...
Müssen wir noch ändern. Hast Du einen Tip, wie wir die entsprechenden Stellen schnell finden und evtl. mit Suchen&Ersetzen ändern können?
(Ändern des Attributs "subtype" mit Wert "dmgh" in den Wert "Werminghoff" dort, wo der Wert des target beginnt mit "http://www.mgh.de/dmgh/resolving/MGH_Conc._2,1" bzw. "_2,2"?)

**Comment by MarcelloPerathoner** [comment]
Die neuen Subtypes sind: Werminghoff1 und Werminghoff2 (in Anlehnung an BK1-BK2, Pertz1-Pertz2)

subtype="dmgh" findet sich nur in wolfenbuettel-hab-blankenb-130.xml. Dann nach "Conc." suchen.
