### ISSUE TITLE
Kollationstool: Versionen mit "Hand X" kollationieren

### ISSUE THREAD

**Issue by laMischke** [cceh/capitularia#6]
@MarcelloPerathoner @domtru @Capitularia-sk 
 Die Fassungen der Texte, die mithilfe des Kollationstools verglichen werden, enthalten keine Korrekturen mit hand="X" (da diese in der HTML-Präsentation nicht im Haupttext erscheinen, sondern nur in den Anmerkungen). 
Kann man als zusätzliche Vergleichsoption bei den Texten, in denen es Korrekturen von Hand X gibt, eine Fassung "nach Korrektur von Hand X" anbieten?

**Comment by MarcelloPerathoner** [comment]
Folgende Teilaufgaben müssen gelöst werden:

1. Das XSLT für Kollationen neu schreiben (basierend auf XSLT für Wordpress) (fertig)
2. Dem XSLT eine Option für die Ausgabe von späteren Händen hinzufügen
3. Einen Weg finden, diese Option zu übergeben.
4. Testen ob eine Hs eine spätere Hand enthält.
5. Eine weitere virtuelle Hs. in der Kollation hinzufügen.
