### ISSUE TITLE
leere Fußnote

### ISSUE THREAD

**Issue by domtru** [cceh/capitularia#65]
Handschrift Paris 4761-1-2:
`<ab type="meta-text" corresp="BK.77_20_inscriptio" xml:id="paris-bn-lat-4761-1-2-120v-1"
               ><seg type="num" n="19">XVIII<add>I</add></seg></ab>`

Das add-Element erzeugt zwar eine Fußnote, diese hat aber keinen Inhalt, sodass nur ein kleiner leerer Pop-Up angezeigt wird.

**Comment by laMischke** [comment]
@Capitularia-sk @domtru @skheinen 

Genau dasselbe auch in paris-bn-lat-9654:
```
<ab type="meta-text" xml:id="paris-bn-lat-9654-70r-5" corresp="BK.195_1_inscriptio">DE <choice>
                    <abbr>INSCRIPT</abbr>
                    <expan>INSCRIPTIONE</expan>
                </choice> TEMPORUM <lb/>
            </ab>
```
Es gibt eine Fußnote, aber das Popup-Fenster ist leer.

**Comment by laMischke** [comment]
@Capitularia-sk @domtru @skheinen 

Leider taucht das Problem noch immer auf ... und zwar in selestat-bh-14:
 ```
<ab type="meta-text" xml:id="selestat-bh-14-113r-11"
            corresp="BK.156_2_inscriptio_c Ansegis.4_26bis_inscriptio_c">
            <seg type="num" n="25">XXV</seg>
            <del>D</del> qualiter de statu suo pulsatus euindicet libertatem suam<note
               type="editorial">Im folgenden Textblock (...).</note> . <lb/>
         </ab>
```
Sowohl für das del nach dem seg wie auch für die note erscheint in HTML nur ein leeres Popup-Fenster.

**Comment by MarcelloPerathoner** [comment]
Das liegt daran, daß der vorhergehende milestone kein unit=capitulatio enthält. Ich habe diese Bedingung jetzt entfernt.
