### ISSUE TITLE
Absatz nach anchor oder milestone mitten im Text?

### ISSUE THREAD

**Issue by laMischke** [cceh/capitularia#66]
@Capitularia-sk @domtru @skheinen 

Handschrift paris-bn-lat-9654:

Mitten im ab kommt plötzlich ein Absatz, und zwar an dieser Stelle nach "uendicet":
```
... uendicet . <anchor
                    xml:id="paris-bn-lat-9654-70r-6_2"/>
                <milestone unit="span" corresp="BK.195_2" spanTo="#paris-bn-lat-9654-70r-6_3"/>Qui
                si <lb/> infra <num>XXX</num> annos ...
```
Kurz davor (scheinbar?) die gleiche Codierung, aber hier wird kein neuer Absatz/Zeilenwechsel generiert:

```
 ... posse sufficere * <anchor xml:id="paris-bn-lat-9654-70r-6_1"/>
                <lb/>
                <milestone unit="span" corresp="BK.195_2_inscriptio"
                    spanTo="#paris-bn-lat-9654-70r-6_2"/><seg type="initial">S</seg>i quis colonum
                alienum in re sua <num>XXX</num> annos habuerit . acsi suum ...
```

**Comment by domtru** [comment]
Problem: Bei `<milestone unit ="capitulare">` innerhalb eines ab wird in der HTML-Präsentation ein störender Absatz gemacht. Beispiel in Paris Lat. 4417 (`xml:id="paris-bn-lat-4417-259r-4"`)

**Comment by domtru** [comment]
@laMischke @Capitularia-sk @skheinen 

Weiteres Problem: Wenn ein `<milestone unit="span">` gesetzt wird, wird an der entsprechenden Stelle in der HTML-Präsentation der Text eingerückt, was aber nicht so sein soll. 

Beispiele: 

Berlin Phill. 1737:
`
<ab corresp="BK.192_11 BK.192_12 BK.192_15 BK.192_13" type="text"
             xml:id="berlin-sb-phill-1737-48r-2">
             <milestone unit="span" corresp="BK.192_11"
                spanTo="#berlin-sb-phill-1737-48r-2_1"/>
             <seg rend="coloured" type="initial">D</seg>e pontibus publicis destructis <lb/>placuit
             nobis ut hi qui iussionem nostram in reparandis pontibus...
`
Das "De" erscheint korrekt als farbige Initiale, aber eingerückt durch vorangehendes Leerzeichen (http://capitularia.uni-koeln.de/mss/berlin-sb-phill-1737/). Ebenso verhält es sich mit dem oben genannten Beispiel in Paris Lat. 4417.
