### ISSUE TITLE
Digitalisat Kopenhagen

### ISSUE THREAD

**Issue by domtru** [cceh/capitularia#67]
@Capitularia-sk 
Bei der Handschrift Kopenhagen 1943 (http://capitularia.uni-koeln.de/mss/kopenhagen-kb-1943-4/) ist bei der Angabe "Digitalisat verfügbar bei..." das Feld leer, wo die entsprechende Institution stehen müsste, hier sollte also stehen "Digitalisat verfügbar bei Det Kongelige Bibliotek" (http://www.kb.dk/permalink/2006/manus/84/eng/)

**Comment by laMischke** [comment]
Bei der Gelegenheit bitte auch folgende Angabe korrigieren:

In trier-sb-1362a-110a steht unter "Digitalisat verfügbar bei ..." 
"Die ältesten deutschsprachigen Texte der **trierer** Stadtbibliothek"; bitte "**Trierer**" großschreiben!
(Link zum Digitalisat: http://www.trierer-handschriften.de/capitulare_handschrift.html)

**Comment by laMischke** [comment]
@Capitularia-sk @domtru @skheinen 

Bei Cambridge, Parker Library wird beim Link auf das Digitalisat ebenfalls kein Name angegeben; hier sollte stehen:
"Digitalisat verfügbar bei der Parker Library."
Betrifft folgende Links:
- https://parker.stanford.edu/parker/catalog/xd738fw2393
- https://parker.stanford.edu/parker/catalog/nh277tk2537
in den Dateien cambridge-ccc-57 und cambridge-ccc-265.

**Comment by laMischke** [comment]
@Capitularia-sk @domtru @skheinen 

Neue Verlinkung (in newhaven-bl-413):
http://brbl-dl.library.yale.edu/vufind/Record/3527259;

bitte für die Links mit diesem URL-Anfang folgenden Text anzeigen:
"Digitalisat verfügbar bei **Beinecke Digital Collections**"
