### ISSUE TITLE
Änderungen in publ/capit/pre814 sind verschwunden

### ISSUE THREAD

**Issue by laMischke** [cceh/capitularia#7]
@MarcelloPerathoner @domtru @Capitularia-sk @skheinen 

Hallo Marcello,
wir stellen gerade durch Zufall fest, dass alle Kapitularienseiten, die im Ordner publ/capit/pre814 am 19./20. Januar 2017 geändert worden sind (nicht von uns!), und danach sind alle Aktualisierungen, die wir im November 2016 bzw. früher vorgenommen haben, verlorengegangen.

Beispiel: http://capitularia.uni-koeln.de/capit/pre814/bk-nr-021/

Bei den Revisions auf Wordpress ist der kritische Moment hier zu sehen (19. Januar, 20.36 Uhr):
http://capitularia.uni-koeln.de/wp-admin/revision.php?revision=13822

Jetzt sind wir ein bisschen in Panik ... kannst Du rekonstruieren, wie es dazu gekommen ist?
Und hast Du irgendwo noch die alten Dateiversionen verfügbar?

**Comment by MarcelloPerathoner** [comment]
On 03/06/2017 11:45 AM, laMischke wrote:
> @MarcelloPerathoner @domtru @Capitularia-sk @skheinen
>
> Hallo Marcello, wir stellen gerade durch Zufall fest, dass alle
> Kapitularienseiten, die im Ordner publ/capit/pre814 am 19./20. Januar
> 2017 geändert worden sind (nicht von uns!), und danach sind alle
> Aktualisierungen, die wir im November 2016 bzw. früher vorgenommen
> haben, verlorengegangen.
>
> Beispiel: http://capitularia.uni-koeln.de/capit/pre814/bk-nr-021/
>
> Bei den Revisions auf Wordpress ist der kritische Moment hier zu
> sehen (19. Januar, 20.36 Uhr):
> http://capitularia.uni-koeln.de/wp-admin/revision.php?revision=13822
>
> Jetzt sind wir ein bisschen in Panik ... kannst Du rekonstruieren,
> wie es dazu gekommen ist? Und hast Du irgendwo noch die alten
> Dateiversionen verfügbar?
>

Da liegt ein Mißverständnis des Workflows vor.

Die Kapitularienseiten in /capit/ werden per Skript generiert und 
sollten nicht von Hand editiert werden.


Änderungen sollen nur an der Datei

   capit/lists/capit_all.xml

vorgenommen werden, die dann mit dem Skript

   transform/Kapitularienseiten_generieren.xsl

in die Kapitularienseiten geschrieben werden.


Offensichtlich wurden am 20.01. die Kapitularienseiten neu generiert, um 
die @corresp-Attribute zu ergänzen.

Ich habe zwar ein Backup < 20.01. aber das hilft uns nicht weiter da 
eure Änderungen nicht in der capit_all.xml stehen.




Regards

-- 
Marcello Perathoner
webmaster@gutenberg.org

**Comment by laMischke** [comment]
@MarcelloPerathoner @Capitularia-sk @skheinen @domtru 

Da gibt es offenbar wirklich ein Missverständnis ... die Datei capit_all liegt zwar vielen unserer Listen zugrunde, sie soll aber nicht für die einzelnen Kapitularienseiten verwendet werden. Das haben wir offenbar nicht explizit besprochen, nachdem Daniela weg ist.
Die sind einmal neu generiert worden und liegen seitdem in unterschiedlichen (nach zeitlichen Abschnitten geordneten) Ordnern auf dem Server: ltr - post840 - pre814 - undated.
Dort bearbeiten wir die einzelnen xml-Dateien; die Kapitularienseiten sollen also - im Unterschied zu den Listen - aus diesen Ordnern generiert werden.
Ich habe eine Sicherungskopie des Ordners pre814 vom Dezember, den würde ich jetzt auf den Server aufspielen (oder soll ich noch warten?).
Sollen wir uns sicherheitshalber kurz treffen, um das zu besprechen? Ich hätte heute zwischen ca. 14.30 - 15.30 Uhr Zeit.
