### ISSUE TITLE
Mehrfache <title> in <msItem corresp="...">

### ISSUE THREAD

**Issue by MarcelloPerathoner** [cceh/capitularia#71]
Was tun bei mehrfachen @corresp / &lt;title&gt; wie z.B. in paris-bn-lat-10758:
&lt;msItem corresp="BK.192 Ansegis BK.191 BK.77" n="54"&gt;?
Es ist keine eindeutige Zuordnung von @corresp und &lt;title&gt; festgehalten.

**Comment by laMischke** [comment]
@Capitularia-sk @domtru @skheinen 
Wir haben überlegt, den `title`-tags zusätzlich Attribute mit dem jeweiligen BK-Wert zu geben; dann ist die Zuordnung eindeutig.
Dazu müsstest Du bitte 
a) in allen Dateien den `title`-tags, die sich in einem msItem befinden, ein @corresp mit demselben Wert wie dasjenige im `msItem`-tag zuordnen und 
b) uns Bescheid geben, in welchen Dateien sich die Fälle finden, in denen ein msItem mehrere titles bzw. Werte für @corresp hat, damit wir sie manuell nachbearbeiten (am liebsten mit dem XSPath-Ausdruck, mit dem wir die betreffenden Stellen in den Dateien wiederfinden)!
c) Das Skript für die Verarbeitung des headers (mss-header.xsl?) muss so angepasst werden, dass die Verlinkung zu den entsprechenden Kapitularienseiten nicht mehr über die @corresp in `msItem` läuft, sondern über die @corresp in den `title`-tags.

**Comment by MarcelloPerathoner** [comment]
publ/mss/bamberg-sb-can-12.xml BK.186 BK.186
publ/mss/blois-adlc-fragment.xml Ansegis BK.151
publ/mss/gotha-flb-memb-i-84.xml BK.112 BK.105
publ/mss/laon-bm-265.xml BK.16 Mordek.4
publ/mss/laon-bm-265.xml BK.16 BK.15
publ/mss/mailand-ba-a-46.xml Ansegis BK.153
publ/mss/mailand-ba-o-55.xml BK.168 BK.100
publ/mss/mailand-ba-o-55.xml BK.228 BK.105
publ/mss/muenchen-bsb-lat-14727.xml BK.116 BK.40
publ/mss/muenchen-bsb-lat-6360.xml BK.287 BK.130
publ/mss/muenchen-ub-fragmente.xml BK.163 BK.175 BK.165
publ/mss/muenchen-ub-fragmente.xml BK.193 BK.209 BK.210
publ/mss/paris-bn-lat-10758.xml BK.104 Mordek.27
publ/mss/paris-bn-lat-10758.xml BK.189 BK.188
publ/mss/paris-bn-lat-10758.xml BK.192 Ansegis BK.191 BK.77
publ/mss/paris-bn-lat-1455.xml Mordek.1 BK.1 BK.5
publ/mss/paris-bn-lat-1567.xml BK.293 BK.257
publ/mss/paris-bn-lat-18237.xml BK.20a BK.93
publ/mss/paris-bn-lat-3851.xml Ansegis BenedictusLevita
publ/mss/paris-bn-lat-3877.xml Mordek.26 BK.259
publ/mss/paris-bn-lat-4628a.xml BK.192 BK.191 BK.77
publ/mss/paris-bn-lat-4631.xml BK.167 Mordek.27 BK.156
publ/mss/paris-bn-lat-4631.xml BK.191 BK.192
publ/mss/paris-bn-lat-4995.xml BK.62 BK.63
publ/mss/paris-bn-lat-9654.xml BK.65 BK.66
publ/mss/paris-bn-lat-9654.xml BK.186 BK.186
publ/mss/selestat-bh-14.xml BK.138 BK.140
publ/mss/st-petersburg-sb-q-v-ii-11.xml BK.57 Mordek.9
publ/mss/test.xml BK.16 Mordek.4
publ/mss/test.xml BK.16 BK.15
publ/mss/vatikan-bav-barb-lat-679.xml BK.104 BK.92 BK.102
publ/mss/vatikan-bav-pal-lat-582.xml BK.22 Mordek.27
publ/mss/vatikan-bav-pal-lat-582.xml BK.186 BK.186
publ/mss/vatikan-bav-reg-lat-263.xml BK.44 BK.224
publ/mss/vatikan-bav-reg-lat-291.xml BK.298 BK.299
publ/mss/vatikan-bav-reg-lat-291.xml BK.291 BK.257 BK.293
publ/mss/vatikan-bav-reg-lat-417.xml BK.186 BK.186
publ/mss/wolfenbuettel-hab-helmst-532.xml KonzilNeuching KonzilDingolfing
intern/InArbeit/Britta/vatikan-bav-reg-lat-263.xml BK.44 BK.224
intern/InArbeit/Dominik T./gotha-flb-memb-i-84_KOPIE.xml BK.112 BK.105
intern/InArbeit/Dominik T./paris-bn-lat-9654_KOPIE.xml BK.65 BK.66
intern/InArbeit/Dominik T./paris-bn-lat-9654_KOPIE.xml BK.186 BK.186
intern/InArbeit/Soeren/mailand-ba-a-46_3_NK_1.xml Ansegis BK.153

**Comment by MarcelloPerathoner** [comment]
XPath Ausdruck:

//tei:msItem[contains (@corresp, ' ')]

**Comment by laMischke** [comment]
@Capitularia-sk @domtru @skheinen 
Danke!
Außerdem fällt uns gerade auf, dass es auch Dateien gibt, in denen zwar title-tags in den msItems vorhanden sind, aber kein @corresp (auch nicht im msItem). Auch das müssen wir noch händisch nachtragen.
Kannst Du bitte dafür noch eine Abfrage starten und uns die Ergebnisliste zur Verfügung stellen?

**Comment by laMischke** [comment]
@Capitularia-sk @domtru @skheinen 

Die oben (8. Januar) unter b) gelistete Nachbearbeitung haben wir jetzt abgeschlossen (msItems mit mehreren corresp-Werten; jetzt stehen in den title-tags jeweils die korrekt zugeordneten @corresp); allerdings müssen wir noch die Fälle finden, in denen die msItems kein @corresp haben, obwohl title-tags im msItem vorhanden sind (siehe voriger Kommentar). Könntest Du dafür bitte eine Abfrage starten bzw. uns den X-Path-Ausdruck sagen, damit wir das selber tun können?

**Comment by MarcelloPerathoner** [comment]
XPath:

//msItem[not (@corresp)]//title

~ 74 titles

**Comment by laMischke** [comment]
@Capitularia-sk @domtru @skheinen 

OK, auch diesen Nachbearbeitungsschritt haben wir abgeschlossen.
Jetzt könntest Du mit dem Suchen/Ersetzen über alle Dateien starten (Punkte a und c vom 8. Januar, s.o.; wie üblich: vorher bitte Bescheid geben, damit wir nicht gleichzeitig daran arbeiten):

In allen Dateien den title-tags, die sich in einem msItem befinden, ein @corresp mit demselben Wert wie dasjenige im msItem-tag zuordnen (bis auf diejenigen title-tags, die jetzt schon ein @corresp haben).

Außerdem:
Das Skript für die Verarbeitung des headers (mss-header.xsl?) so anpassen, dass die Verlinkung zu den entsprechenden Kapitularienseiten nicht mehr über die @corresp in msItem läuft, sondern über die @corresp in den title-tags.

**Comment by domtru** [comment]
Ergänzung: Wenn alle title-tags das entsprechende corresp erhalten haben, können die corresps aus dem msItem-tag verschwinden, da wir solch eine Dopplung nicht brauchen!

**Comment by domtru** [comment]
Bei den msItems, die nur ein einziges corresp haben, steht dieses corresp immer noch als Attribut im msItem selbst. Das corresp bitte nun in die title-tags verschieben und die Verlinkung entsprechend anpassen.
