### ISSUE TITLE
Worterkennung - Problem bei unclear

### ISSUE THREAD

**Issue by Capitularia-sk** [cceh/capitularia#74]
Ein unclear-tag scheint es in manchen Fällen zu verhindern, dass das Skript korrekt erkennt, was alles zu einem Wort gehört.
Beispiel "alemaniam" aus http://capitularia.uni-koeln.de/mss/vatikan-bav-reg-lat-1283a/
(Dateiende, Anfang des letzten Absatzes)

Hier ist das L nachträglich ergänzt (mit add getaggt) während die folgenden beiden Buchstaben schwer lesbar sind (mit unclear getaggt). Eine manuelle note liefert zusätzliche Informationen.

Kodiert ist das folgendermaßen:

`a<add>l</add><unclear>em</unclear>aniam<note type="editorial"
                        ><mentioned>l</mentioned> ergänzt; schwer lesbar, aber wohl
                        <mentioned>alemaniam</mentioned> und nicht
                        <mentioned>alamaniam</mentioned>.</note>`

Das Skript sieht dort, wo das schließende tag von add auf das öffnende tag von unclear trifft, offenbar ein Wortende und setzt entsprechend die (eigentlich zu unterdrückende) automatische note für add direkt hinter das L, d.h. mitten im Wort.

Evtl. könnte es sich bei dieser Gelegenheit lohnen zu prüfen, ob es auch beim Zusammentreffen einiger weiterer (gar aller?) tags zu diesem Fehler kommt. Ein erster Test zeigte keine Probleme bei add auf del, wohl aber bei del auf unclear; letzteres könnte also mit seinen im Wort eingefügten eckigen Klammern der Auslöser sein.

**Comment by MarcelloPerathoner** [comment]
Der Grund ist: die eckige Klammer wird als Wortende erkannt. 
al[em]aniam
