### ISSUE TITLE
Verarbeitung von tags in manuellen Fußnoten

### ISSUE THREAD

**Issue by domtru** [cceh/capitularia#75]
@laMischke @Capitularia-sk @skheinen  

Ist es möglich, tags, die in den Transkriptionen verwendet werden, auch in manuellen Fußnoten (`note type="editorial">`) zu benutzen und diese entsprechend ausgeben zu lassen? Also z.B. `<seg type="initial" rend="coloured">`, was dann auch in der manuellen note fett und farbig ausgegeben wird. Oder auch `<gap unit="chars" quantity="3">` , was dann entsprechend mit "[...]" ausgegeben wird. 
Oder gibt es bei der Darstellung in den PopUp-Fenstern Probleme?

**Comment by MarcelloPerathoner** [comment]
Das müßte gehen. Einfach ausprobieren.

**Comment by domtru** [comment]
Funktioniert soweit tatsächlich, `seg type="initial"` wird allerdings nicht fett ausgegeben
