### ISSUE TITLE
Formulierung für Makro

### ISSUE THREAD

**Issue by laMischke** [cceh/capitularia#8]
@domtru @Capitularia-sk @skheinen 

Vorschlag für Formulierung für die Zitierempfehlung (bitte ändern, falls nötig; danach an Marcello):

[Autor - steht in p style="text-align: right;font-style: italic"], [Titel des Blogposts], in: Capitularia. Edition der fränkischen Herrschererlasse, bearb. von Karl Ubl und Mitarb., Köln 2014 ff. URL: http://capitularia.uni-koeln.de/mss/[slug-des-blogposts] (abgerufen am: [aktuelles Datum])

**Comment by laMischke** [comment]
@MarcelloPerathoner @domtru @Capitularia-sk @skheinen 

Vorschlag für Formulierung für die Zitierempfehlung (auf allen Blogposts, deren slug http://capitularia.uni-koeln.de/blog/handschrift-des-monats-[...]/ bzw. /kapitular-des-monats-[...] enthält):

[Autor - steht in p style="text-align: right;font-style: italic"], [Titel des Blogposts], in: Capitularia. Edition der fränkischen Herrschererlasse, bearb. von Karl Ubl und Mitarb., Köln 2014 ff. URL: http://capitularia.uni-koeln.de/mss/[slug-des-blogposts] (abgerufen am: [aktuelles Datum])

**Comment by MarcelloPerathoner** [comment]
Shortcode ist: [cite_as]

**Comment by laMischke** [comment]
@MarcelloPerathoner @domtru @Capitularia-sk @skheinen 

Fast perfekt - bis auf den Autornamen: Kann man den auch inklusive Groß-/Kleinschreibung und Leer- und sonstigen Zeichen auslesen? Sonst wird "B. Mischke" zu "bmischke" (was als offizielle Zitierempfehlung etwas zu salopp wäre).

**Comment by MarcelloPerathoner** [comment]
Du mußt in Deinem Profil Deinen richtigen Namen eintragen, dann wird er auch so angezeigt.

Falls der Autor nicht immer der "Autor laut Wordpress" ist, kann ich ein Parameter hinzufügen (das mit dem Auslesen des Autors aus dem Text klappt nicht ohne weiteres). Bei abweichendem Autor würde man dann schreiben:

  [cite_as author="K. Ubl"]

Soll ich das so machen?

**Comment by laMischke** [comment]
Ja, das wäre die beste Lösung - meistens bin nämlich ich diejenige,  
die die Blogposts online stellt, damit wäre der "Autor laut Wordpress"  
relativ selten identisch mit dem "wahren Autor".



-- 
Dr. Britta Mischke
Arbeitsstelle "Edition der fränkischen Herrschererlasse"
Historisches Institut
Universität zu Köln
Meister-Ekkehart-Str. 11
50937 Köln

Tel. (0221) 470 6852

Postanschrift:
Historisches Institut
Universität zu Köln
Albertus-Magnus-Platz
50923 Köln

http://capitularia.uni-koeln.de/
