### ISSUE TITLE
gap in del: Mit † anzeigen lassen

### ISSUE THREAD

**Issue by laMischke** [cceh/capitularia#80]
@Capitularia-sk @domtru @skheinen 

Wenn `gap` in `del` geschachtelt ist (kann auch innerhalb von `subst` vorkommen), soll die Anzahl der ausgefallenen Buchstaben NICHT wie sonst bei `gap` mit Pünktchen angezeigt werden, sondern mit dem Symbol, das bei `del` verwendet wird (†).

**Comment by laMischke** [comment]
@Capitularia-sk @domtru @skheinen 

Ergänzung: 
Leeres `gap`-Element in `subst`/`del` verarbeiten zu "[†]" (wie bei leerem `del` in `subst`).

Um die alten Dateien aufzuräumen, bräuchten wir noch die Treffer von zwei Abfragen:
1. Steht in den XML-Dateien irgendwo noch (händisch eingefügtes) "[†]" in `subst`/`del`?
2. Steht ebd. irgendwo noch `gap` mit @quantity und @unit innerhalb von `subst`/`del`?

**Comment by MarcelloPerathoner** [comment]
XPath 2-0 Abfragen für 1. und 2. :

//subst//del[contains (., '[†]')]
//subst//del//gap[@quantity or @unit]

**Comment by domtru** [comment]
@laMischke @Capitularia-sk 

Ergänzung zu diesem Issue: gap (mit oder ohne unit und quantity) in normalem del (also nicht subst/del) soll so ausgegeben werden wie alleinstehendes gap bzw. wie es in der Legende steht. Also: gap mit quantity Kreuze (Anzahl nach quantity-Wert, ohne Klammern), gap ohne quantity Kreuz in eckigen Klammern. 

Beispiel: Paris Lat. 4626 p. 74 (BK 266 A c. 4, Anmerkung zu "de"): `<del>h<gap unit="chars" quantity="2"/></del>` wird ausgegeben als "folgt getilgtes h[††]". Hier müssen also die eckigen Klammern weg. Wenn dort nur gap stünde, wäre ein Kreuz in eckigen Klammern korrekt.
