### ISSUE TITLE
Neues Element gap reason="editorial" bei lb mit n-Wert einfügen

### ISSUE THREAD

**Issue by laMischke** [cceh/capitularia#81]
@Capitularia-sk @domtru @skheinen 

Wir möchten in Zukunft explizite Hinweise auf von uns beim Transkribieren ausgelassenen Text geben.
Dazu soll im body nach jedem lb mit einem n-Attribut ein neues Element eingefügt werden:

`gap reason="editorial"`

Dieses Element soll in HTML wie folgt verarbeitet werden:

"**[_Nicht transkribierter Text_]**" - alles fett, eckige Klammern recte, Text kursiv; linksbündig ausrichten.

**Comment by domtru** [comment]
@Capitularia-sk @domtru @skheinen

Wir möchten in Zukunft explizite Hinweise auf von uns beim Transkribieren ausgelassenen Text geben.
Dazu soll im body VOR jeder Kombination aus cb und anschließendem lb (nur außerhalb von ab)  ein neues Element eingefügt werden:

`gap reason="editorial"`

Das erste cb/lb-Kombination in der Datei soll dabei ausgelassen werden. Bitte in allen mss-Dateien (auch im Ordner "InArbeit") durchführen. Die Ausgabe dieses tags funktioniert bereits.

**Comment by MarcelloPerathoner** [comment]
Publizierte Dokumente wurden editiert. Bitte überprüfen.
Nach Absprache werden dann noch die Dokumente InArbeit editiert.
