### ISSUE TITLE
Adressen von Schema und Schematron im Dateikopf auf GitHub umstellen

### ISSUE THREAD

**Issue by laMischke** [cceh/capitularia#86]
Bitte im Dateikopf aller Dateien (in publ/mss und InArbeit mit Unterordnern) folgende Adressen ändern:

`?xml-model href="http://capitularia.uni-koeln.de/cap/publ/schemata/capitularia-msDesc-Transcription.rnc" type="application/relax-ng-compact-syntax"?`

ändern zu

**`?xml-model href="https://github.com/cceh/capitularia-tei-qm/blob/master/schema/capitularia-msDesc-Transcription.rnc" type="application/relax-ng-compact-syntax"?`**

und
`?xml-model href="http://capitularia.uni-koeln.de/cap/intern/InArbeit/capitularia.sch" type="application/xml"
schematypens="http://purl.oclc.org/dsdl/schematron"?`

ändern zu

**`?xml-model href="https://github.com/cceh/capitularia-tei-qm/blob/master/schema/capitularia.sch" type="application/xml"
schematypens="http://purl.oclc.org/dsdl/schematron"?`**

**Comment by laMischke** [comment]
Bezieht sich das "wird komplizierter" auf das Einbinden der Adressen in die Dateien generell oder nur auf meine zusätzliche Frage, wie wir selber Änderungen an der Schemadatei vornehmen können?
Wenn ersteres: Würde das Öffentlichmachen des Repositorys das Problem lösen? Was sprach nochmal dagegen (außer einem grundsätzlichen Unwohlsein beim Zugänglichmachen aller Daten)?

**Comment by MarcelloPerathoner** [comment]
Das bezieht sich auf das Einbinden der Datein in Oxygen. Das Öffentlichmachen des Repositorys würde dieses Problem auf einfache Weise lösen. Ich hatte nur den Eindruck, daß das Martina nicht ganz recht sei. Von meiner Seite spricht nichts dagegen. Du kannst ja noch mal mit ihr reden.
Wenn ihr die Dateien selber ändern wollt, so könnt ihr es schon jetzt tun. Dazu müßt ihr das Repository clonen, die Dateien lokal ändern und dann wieder pushen.

**Comment by laMischke** [comment]
@Capitularia-sk @domtru @skheinen 

Nach Rücksprache mit Martina liegen die Schema- und Schematron-Dateien jetzt im Haupt-Repository unter /schemas - dann können wir die Änderungen der Adressen im Dateikopf aller Dateien (in publ/mss und InArbeit mit Unterordnern) jetzt starten, oder?
Gib uns bitte wieder kurz vorher Bescheid, wenn Du Zeit dafür hast, damit wir nicht zur selben Zeit an unseren Dateien arbeiten!

**Comment by MarcelloPerathoner** [comment]
Oxygen holt sich die Schemata nun direkt vom github-Hauptverzeichnis. 
Wir müssen die Dateien nicht anpassen. Die Anfragen werden von unserem Server zu github umgeleitet.

**Comment by laMischke** [comment]
@Capitularia-sk @domtru @skheinen 

D. h. die Adressen im Dateikopf können so stehenbleiben?

**Comment by MarcelloPerathoner** [comment]
Ja.

**Comment by textloop** [comment]
> Das bezieht sich auf das Einbinden der Datein in Oxygen. Das Öffentlichmachen des Repositorys würde dieses Problem auf einfache Weise lösen. 

Variante A: 

Wir können das öffentlich machen, ist kein Problem. @laMischke: man kann dann aber unsere Issuediskussionen auch sehen, nur das dir das bewusst ist. Wäre aber aus meiner Sicht nicht schlimm.

Variante B:
Eine andere Möglichkeit wäre, wir schließen https://github.com/cceh/capitularia-tei-qm und zeihen die dateien um in https://github.com/cceh/capitularia. 

Die Entwicklungsarbeit am QM über Schema und Schematron ist ja weitesgehend abgeschlossen. Falls doch nochmal was ist würde ich dann Pull requests stellen.

ich stimme für Variante B.

**Comment by laMischke** [comment]
@textloop 
Mir ist es gleich; wenn Martina für Variante B ist, schließe ich mich an.
Ist vielleicht auch besser, alles an einem Ort zu haben?!

**Comment by textloop** [comment]
Alles klar, sehr gut. 
Dann versuchen ich und @laMischke mal alle in https://github.com/cceh/capitularia-tei-qm noch offenen Issues zu schleißen und dann archiviere ich das Repository. Damit ist dann eindeutig, dass dort nichts mehr gepflegt wird.
