### ISSUE TITLE
Neuer subtype für ref type="internal"

### ISSUE THREAD

**Issue by laMischke** [cceh/capitularia#88]
@Capitularia-sk @domtru @skheinen 

Wenn im Header in `bibl resp=”capit”`
ein `ref  type=”internal” subtype=”mom” target=”handschrift-des-monats-august-2016″/` steht,
wird daraus ein Link generiert **Zum Artikel in der Rubrik "Handschrift des Monats"**.

Neu: Wenn subtype="com" [Capitulary of the Month],
soll der Link lauten: **Zum Artikel in der Rubrik "Kapitular des Monats"**.

Könnte man solche Links auch auf den Kapitularienseiten (Dateien in http://capitularia.uni-koeln.de/capit) einfügen? Ganz unten positioniert und mit einem Trennstrich abgegrenzt?

**Comment by laMischke** [comment]
@Capitularia-sk @domtru @skheinen 

Funktioniert, Danke!
Wie immer haben wir, nachdem wir das Ergebnis gesehen haben, noch ein paar Folgewünsche:
- Auf den Kapitularienseiten: vor dem Link "Zum Artikel in der Rubrik "Kapitular des Monats"" keinen Trennstrich und keine schwarze Überschrift "Artikel", sondern nur der Link nach einer Leerzeile nach dem vorangehenden letzten Abschnitt
- danach: nach einem Trennstrich, wie auf den Handschriftenseiten, "Empfohlene Zitierweise" mit automatisch generierter Zitierempfehlung
- danach: Trennstrich, Download etc. (wie jetzt).

**Comment by laMischke** [comment]
@Capitularia-sk @domtru @skheinen 

Sorry, Denkfehler; zu Punkt 1: doch einen Trennstrich vorher. Sonst kann man das von den übrigen Verlinkungen unter "transmission" nicht unterscheiden, solange die Rubrik "literature" noch nicht befüllt ist. Aber keine Überschrift.

**Comment by domtru** [comment]
Wenn es keinen Link zum Artikel "Kapitular des Monats" gibt, erscheinen auf den Kapitularienseiten nun zwei Trennstriche hintereinander (z.B. BK 141 etc. im Gegensatz zu BK 142). Kann man das so regeln, dass in den Fällen, wo es keinen Artikel gibt, nur ein Trennstrich gesetzt wird?
