### ISSUE TITLE
Bibliographie Schema/Schematron

### ISSUE THREAD

**Issue by Capitularia-sk** [cceh/capitularia#93]
Die Bibliographie für die Homepage (auf dem Server :unter publ/bibl/Bibliographie_Capitularia.xml) hat im gleichen Ordner eine Datei "schemas.xml", scheint aber dem header nach (auch/nur?) auf separate, CCeH-eigene Schemadateien zurück zu greifen:

<?xml-model href="../../intern/Bibliographie/cceh-bibliographies.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="../../intern/Bibliographie/cceh-bibliographies.sch" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<?xml-model href="cceh-bibliographies.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="cceh-bibliographies.sch" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>

Folgendes Problem, wofür zunächst zu klären wäre, welche Datei dazu verändert werden müsste und ob diese Datei überhaupt so einfach geändert werden kann (eher nicht, falls sie zugleich für andere CCeH Projekte verwendet wird):

Bandangaben lassen sich auf zweierlei Art kodieren, einmal als
biblScope unit="volume"  (das verwenden wir und nur das wird entsprechend auch vom Skript verarbeitet und auf der Homepage korrekt angezeigt)
und einmal als
biblScope type="vol".

Um zu vermeiden, dass ich das bei neuen Titeln verwechsele, wäre es schön, wenn das type-attribute hier gar nicht mehr als Option erlaubt wäre (biblScope type kommt in der ganzen Datei keinmal vor), so dass die Auswahl automatisch auf die richtige Variante (unit) gelenkt wird.

Möglicherweise würde eine Lösung voraussetzen, dass wir eine oder mehrere eigene Schema/Schematron Dateien anlegen, die künftig vom CCeH Standard abweichen.

**Comment by MarcelloPerathoner** [comment]
Die Datei `schemas.xml` ist unwichtig. Ich habe sie gelöscht.

Maßgebend sind die Dateien `intern/Bibliographie/cceh-bibliographies.*` (bzw. die lokalen Version davon, die im Header von `publ/bibl/Bibliographie_Capitularia.xml` genannt sind).

Woher die Dateien `cceh-bibliographies.*` stammen, kann ich nicht sagen, da sie vor meiner Zeit angelegt wurden.  Am besten Martina Gödel fragen?  Ich vermute schwer, daß wir sie umbenennen und ändern dürfen. Dann müßte man den Header in der `Bibliographie_Capitularia.xml` auch noch ändern.

**Comment by MarcelloPerathoner** [comment]
Habe die drei fraglichen Dateien nun nach `publ/bibl/bibliography.*` kopiert und dort wunschgemäß angepaßt (biblScope erlaubt kein @type mehr). Den Header von `Bibliographie_Capitularia.xml` habe ich auch angepaßt. Wenn weitere lokale Kopien vorliegen müßten sie auf dieselbe Art angepaßt werden.

**Comment by Capitularia-sk** [comment]
Wunderbar, vielen Dank, jetzt funktioniert es wieder wie gewohnt!
