### ISSUE TITLE
Skript ergänzt in html einen Abstand vor Doppelpunkt

### ISSUE THREAD

**Issue by Capitularia-sk** [cceh/capitularia#94]
Verschiedene Dateien, z.B. avranches-bm-145 und bonn-ub-s-402. 
Im header befindet sich innerhalb des tags catchwords ein weiteres tag collation mit folgendem Inhalt (Avranches):

                            <catchwords>Kustoden: <hi rend="italic">I</hi> (8<hi rend="super">v</hi>)
                              bis <hi rend="italic">XIIII</hi> (110<hi rend="super"
                              >v</hi>)</catchwords>

Auf der html-Seite (http://capitularia.uni-koeln.de/mss/avranches-bm-145/) erscheint das als "Kustoden :", was aber nur scheinbar auf einem eingefügten Leerzeichen basiert, tatsächlich aber wohl ein zusätzlicher Abstand ist, der nach dem Wort "Kustoden" vor dem direkt anschließenden Doppelpunkt eingefügt wird. Lässt sich dieser Abstand hier unterdrücken?

**Comment by MarcelloPerathoner** [comment]
Kann ich nicht erkennen. Zwischen 'n' und ':' ist bei mir nichts.

**Comment by Capitularia-sk** [comment]
Ja, ich konnte da bereits einen Tage später auch schon nichts mehr sehen und hatte gedacht, Du hättest das gleich erledigt. Falls es je wieder auftreten sollte, sagen wir Bescheid.
